// Arabic translations for Lab Test Order Modal
export const arabicLabExtensions = {
  // Common Extensions - Arabic
  'common.allPriorities': 'جميع الأولويات',
  'common.allCategories': 'جميع الفئات',
  'common.allStatuses': 'جميع الحالات',
  'common.hours': 'ساعات',
  'common.currency': 'ريال',
  'common.of': 'من',
  'common.step': 'خطوة',
  'common.saveAsDraft': 'حفظ كمسودة',

  // Laboratory Modal Extensions - Arabic
  'lab.newOrder': 'طلب تحليل جديد',
  'lab.createNewTestOrder': 'إنشاء طلب تحليل مختبر جديد',
  'lab.selectPatient': 'اختيار المريض',
  'lab.selectDoctor': 'اختيار الطبيب',
  'lab.selectTests': 'اختيار التحاليل',
  'lab.reviewOrder': 'مراجعة الطلب',
  'lab.submitOrder': 'إرسال الطلب',
  'lab.orderSettings': 'إعدادات الطلب',
  'lab.selectedTests': 'التحاليل المختارة',
  'lab.totalCost': 'التكلفة الإجمالية',
  'lab.estimatedProcessingTime': 'الوقت المقدر للمعالجة',
  'lab.urgentJustification': 'مبرر الاستعجال',
  'lab.urgentJustificationPlaceholder': 'يرجى تقديم مبرر للأولوية العاجلة/الفورية',
  'lab.clinicalNotes': 'الملاحظات السريرية',
  'lab.clinicalNotesPlaceholder': 'أدخل أي معلومات سريرية ذات صلة',
  'lab.expectedDelivery': 'التسليم المتوقع',
  'lab.orderSummary': 'ملخص الطلب',
  'lab.orderDetails': 'تفاصيل الطلب',
  'lab.urgentTests': 'التحاليل العاجلة',
  'lab.fasting': 'صيام مطلوب',
  'lab.specimen.blood': 'دم',
  'lab.specimen.urine': 'بول',
  'lab.specimen.stool': 'براز',
  'lab.specimen.sputum': 'بلغم',
  'lab.specimen.tissue': 'نسيج',
  'lab.specimen.other': 'أخرى',
  'lab.category': 'الفئة',
  'lab.resultsComingSoon': 'النتائج قريباً',
  'lab.resultsDescription': 'ستظهر نتائج التحاليل هنا قريباً',

  // Patients - Arabic Extensions
  'patients.searchPatients': 'البحث عن المرضى...',
  'patients.addNew': 'إضافة مريض جديد',
  'patients.medicalNumber': 'الرقم الطبي',
  'patients.patient': 'المريض',

  // Additional Lab Terms - Arabic
  'lab.reports': 'التقارير',
  'lab.hours': 'ساعات',

  // Sample Label Printer - Arabic
  'lab.printSampleLabels': 'طباعة ملصقات العينات',
  'lab.printLabelsDescription': 'طباعة ملصقات العينات مع الباركود و QR كود',
  'lab.labelSettings': 'إعدادات الملصقات',
  'lab.labelSize': 'حجم الملصق',
  'lab.sizeSmall': 'صغير',
  'lab.sizeMedium': 'متوسط',
  'lab.sizeLarge': 'كبير',
  'lab.selectPrinter': 'اختيار الطابعة',
  'lab.numberOfCopies': 'عدد النسخ',
  'lab.includeOptions': 'خيارات التضمين',
  'lab.includeQRCode': 'تضمين QR كود',
  'lab.includeBarcode': 'تضمين الباركود',
  'lab.orderInformation': 'معلومات الطلب',
  'lab.testsToLabel': 'التحاليل المراد وسمها',
  'lab.labelPreview': 'معاينة الملصق',
  'lab.labels': 'ملصقات',
  'lab.copies': 'نسخ',
  'lab.total': 'المجموع',
  'lab.printLabels': 'طباعة الملصقات',
  'lab.printing': 'جاري الطباعة',

  // Lab Billing Integration - Arabic
  'lab.labBilling': 'فوترة المختبر',
  'lab.labBillingDescription': 'إدارة الفوترة والمدفوعات لطلبات المختبر',
  'lab.billingItems': 'عناصر الفاتورة',
  'lab.additionalCharges': 'رسوم إضافية',
  'lab.globalDiscount': 'خصم عام',
  'lab.taxRate': 'معدل الضريبة',
  'lab.notesPlaceholder': 'ملاحظات إضافية أو تعليمات خاصة',
  'lab.patientInformation': 'معلومات المريض',
  'lab.insuranceClaim': 'مطالبة التأمين',
  'lab.coveragePercentage': 'نسبة التغطية',
  'lab.deductible': 'الحد الأدنى المشترك',
  'lab.preAuthorization': 'الترخيص المسبق',
  'lab.preAuthPlaceholder': 'رقم الترخيص المسبق (اختياري)',
  'lab.setupInsurancePrompt': 'انقر لإعداد مطالبة التأمين',
  'lab.billingSummary': 'ملخص الفاتورة',
  'lab.subtotal': 'المجموع الفرعي',
  'lab.discount': 'خصم',
  'lab.tax': 'ضريبة',
  'lab.insuranceCoverage': 'تغطية التأمين',
  'lab.patientResponsibility': 'مسؤولية المريض',
  'lab.paymentMethod': 'طريقة الدفع',
  'lab.paymentAmount': 'مبلغ الدفع',
  'lab.amountDue': 'المبلغ المستحق',
  'lab.cardDetails': 'بيانات البطاقة',
  'lab.cardNumber': 'رقم البطاقة',
  'lab.expiryDate': 'تاريخ الانتهاء',
  'lab.paymentSummary': 'ملخص الدفع',
  'lab.totalAmount': 'المبلغ الإجمالي',
  'lab.payingAmount': 'المبلغ المدفوع',
  'lab.remainingBalance': 'الرصيد المتبقي',
  'lab.paymentProcessed': 'تم معالجة الدفع',
  'lab.paymentSuccessMessage': 'تم معالجة الدفعة بنجاح',
  'lab.transactionId': 'رقم المعاملة',
  'lab.amountPaid': 'المبلغ المدفوع',
  'lab.generateInvoice': 'إنشاء فاتورة',
  'lab.processPayment': 'معالجة الدفع',
  'lab.processing': 'جاري المعالجة',
  'lab.downloadReceipt': 'تحميل الإيصال',

  // Lab Notification System - Arabic
  'lab.notificationSystem': 'نظام الإشعارات',
  'lab.notificationSystemDescription': 'إدارة وإرسال الإشعارات عند جاهزية النتائج',
  'lab.pendingNotifications': 'الإشعارات المعلقة',
  'lab.notificationTemplates': 'قوالب الإشعارات',
  'lab.notificationHistory': 'سجل الإشعارات',
  'lab.autoNotifications': 'إشعارات تلقائية',
  'lab.sendPendingNotifications': 'إرسال الإشعارات المعلقة',
  'lab.searchResults': 'البحث في النتائج...',
  'lab.noPendingNotifications': 'لا توجد إشعارات معلقة',
  'lab.noPendingNotificationsDescription': 'جميع النتائج المكتملة تم إرسال إشعاراتها',
  'lab.sendSelected': 'إرسال المحدد',
  'lab.recipient': 'المستقبل',
  'lab.recipientType': 'نوع المستقبل',
  'lab.sentAt': 'تاريخ الإرسال',
  'lab.deliveryAttempts': 'محاولات التسليم',
  'lab.sent': 'مرسل',
  'lab.delivered': 'مُسلم',
  'lab.read': 'مقروء',
  'lab.failed': 'فشل',
  'lab.noNotificationHistory': 'لا يوجد سجل إشعارات',
  'lab.noNotificationHistoryDescription': 'لم يتم إرسال أي إشعارات بعد',
  'lab.autoNotificationSettings': 'إعدادات الإشعارات التلقائية',
  'lab.enableAutoNotifications': 'تفعيل الإشعارات التلقائية',
  'lab.autoNotificationDescription': 'إرسال إشعارات تلقائية عند اكتمال النتائج',
  'lab.notificationDelay': 'تأخير الإشعار',
  'lab.notificationDelayDescription': 'وقت التأخير قبل إرسال الإشعار التلقائي',
  'lab.notifications': 'الإشعارات',
  'lab.patient': 'مريض',
  'lab.doctor': 'طبيب',
  'lab.lab_staff': 'طاقم المختبر',
  'lab.notified': 'تم الإشعار',
  'lab.notificationsSent': 'تم إرسال الإشعارات',
  'lab.notificationError': 'خطأ في إرسال الإشعار',

  // Billing terms - Arabic
  'billing.cash': 'نقدي',
  'billing.creditCard': 'بطاقة ائتمان',
  'billing.insurance': 'تأمين',
  'billing.bankTransfer': 'تحويل بنكي',
  'billing.subject': 'الموضوع',
  'billing.insuranceId': 'رقم التأمين',
  'billing.insuranceProvider': 'مقدم التأمين',
  'billing.quantity': 'الكمية',
  'billing.notes': 'ملاحظات',

  // Additional Lab Management - Arabic
  'lab.billing': 'الفوترة',
  'lab.billingManagement': 'إدارة الفوترة',
  'lab.manageBillingAndPayments': 'إدارة الفوترة والمدفوعات',
  'lab.availableTests': 'التحاليل المتاحة',
  'lab.manageLabTests': 'إدارة تحاليل المختبر',
  'lab.viewAndManageResults': 'عرض وإدارة النتائج',
  'lab.specimen': 'العينة',
  'lab.processingTime': 'وقت المعالجة',
  'lab.preparation': 'التحضير',
  'lab.price': 'السعر',
  'lab.normal': 'طبيعي',
  'lab.low': 'منخفض',
  'lab.high': 'مرتفع',
  'lab.critical': 'حرج',
  'lab.routine': 'عادي',
  'lab.urgent': 'عاجل',
  'lab.stat': 'فوري',

  // Reports System - Arabic
  'reports.systemReports': 'تقارير النظام',
  'reports.systemReportsDescription': 'تقارير شاملة لأداء النظام وإحصاءات المستشفى',
  'reports.systemReportsDesc': 'أداء النظام والإحصائيات التقنية',
  'reports.patientReports': 'تقارير المرضى',
  'reports.patientReportsDesc': 'ديموجرافيا المرضى والزيارات والنتائج',
  'reports.financialReports': 'التقارير المالية',
  'reports.financialReportsDesc': 'الإيرادات والمصروفات وتحليلات الفوترة',
  'reports.staffReports': 'تقارير الموظفين',
  'reports.staffReportsDesc': 'أداء الموظفين والإنتاجية',
  'reports.operationalReports': 'التقارير التشغيلية',
  'reports.operationalReportsDesc': 'الكفاءة التشغيلية ومؤشرات الأداء الرئيسية',
  
  // Report Filters - Arabic
  'reports.filters': 'المرشحات',
  'reports.filtersDescription': 'حدد معايير التقرير والنطاق الزمني',
  'reports.dateRange': 'النطاق الزمني',
  'reports.fromDate': 'من تاريخ',
  'reports.toDate': 'إلى تاريخ',
  'reports.selectDate': 'اختر التاريخ',
  'reports.today': 'اليوم',
  'reports.yesterday': 'أمس',
  'reports.last7Days': 'آخر 7 أيام',
  'reports.last30Days': 'آخر 30 يوماً',
  'reports.last90Days': 'آخر 90 يوماً',
  'reports.thisMonth': 'هذا الشهر',
  'reports.lastMonth': 'الشهر الماضي',
  'reports.thisYear': 'هذا العام',
  'reports.custom': 'مخصص',
  'reports.department': 'القسم',
  'reports.category': 'الفئة',
  'reports.priority': 'الأولوية',
  'reports.applyFilters': 'تطبيق المرشحات',
  'reports.saveTemplate': 'حفظ القالب',
  'reports.templateName': 'اسم القالب',
  
  // Report Categories - Arabic
  'reports.allCategories': 'جميع الفئات',
  'reports.performance': 'الأداء',
  'reports.security': 'الأمان',
  'reports.usage': 'الاستخدام',
  'reports.errors': 'الأخطاء',
  'reports.maintenance': 'الصيانة',
  'reports.demographics': 'الديموجرافيا',
  'reports.visits': 'الزيارات',
  'reports.conditions': 'الحالات الطبية',
  'reports.outcomes': 'النتائج',
  'reports.satisfaction': 'الرضا',
  'reports.revenue': 'الإيرادات',
  'reports.expenses': 'المصروفات',
  'reports.billing': 'الفوترة',
  'reports.insurance': 'التأمين',
  'reports.collections': 'التحصيل',
  'reports.attendance': 'الحضور',
  'reports.productivity': 'الإنتاجية',
  'reports.training': 'التدريب',
  'reports.efficiency': 'الكفاءة',
  'reports.quality': 'الجودة',
  'reports.safety': 'السلامة',
  'reports.capacity': 'السعة',
  'reports.workflow': 'سير العمل',
  
  // Export Options - Arabic
  'reports.export': 'تصدير',
  'reports.exportReport': 'تصدير التقرير',
  'reports.exportDescription': 'اختر تنسيق التصدير والخيارات',
  'reports.selectFormat': 'اختر التنسيق',
  'reports.fileName': 'اسم الملف',
  'reports.exportOptions': 'خيارات التصدير',
  'reports.pageSize': 'حجم الصفحة',
  'reports.orientation': 'الاتجاه',
  'reports.portrait': 'عمودي',
  'reports.landscape': 'أفقي',
  'reports.includeCharts': 'تضمين الرسوم البيانية',
  'reports.includeData': 'تضمين البيانات',
  'reports.reportSummary': 'ملخص التقرير',
  'reports.reportType': 'نوع التقرير',
  'reports.records': 'السجلات',
  'reports.generatedAt': 'تاريخ الإنشاء',
  'reports.estimatedSize': 'الحجم المتوقع',
  'reports.exportNow': 'تصدير الآن',
  
  // Export Formats - Arabic
  'reports.pdfDescription': 'مستند PDF مع تنسيق محفوظ',
  'reports.excelDescription': 'جدول بيانات Excel قابل للتحرير',
  'reports.csvDescription': 'بيانات منفصلة بفواصل للاستيراد',
  'reports.jsonDescription': 'بيانات منظمة للتطبيقات',
  'reports.charts': 'رسوم بيانية',
  'reports.formatting': 'تنسيق',
  'reports.headers': 'عناوين',
  'reports.data': 'بيانات',
  'reports.formulas': 'معادلات',
  'reports.import': 'استيراد',
  'reports.api': 'واجهة برمجة التطبيقات',
  
  // Scheduled Export - Arabic
  'reports.scheduledExport': 'تصدير مجدول',
  'reports.frequency': 'التكرار',
  'reports.time': 'الوقت',
  'reports.emailTo': 'إرسال إلى',
  'reports.daily': 'يومي',
  'reports.weekly': 'أسبوعي',
  'reports.monthly': 'شهري',
  'reports.quarterly': 'ربع سنوي',
  'reports.scheduleExport': 'جدولة التصدير',
  
  // Export Progress - Arabic
  'reports.preparingExport': 'تحضير التصدير',
  'reports.generatingExport': 'إنشاء التصدير',
  'reports.exportComplete': 'اكتمل التصدير',
  'reports.exportError': 'خطأ في التصدير',
  'reports.preparingDescription': 'جاري تحضير بيانات التقرير...',
  'reports.generatingDescription': 'جاري إنشاء الملف...',
  'reports.completeDescription': 'تم تصدير التقرير بنجاح!',
  'reports.errorDescription': 'حدث خطأ أثناء التصدير. يرجى المحاولة مرة أخرى.',
  'reports.preparingData': 'تحضير البيانات',
  'reports.generatingReport': 'إنشاء التقرير',
  
  // Departments - Arabic
  'departments.medicine': 'الطب الباطني',
  'departments.surgery': 'الجراحة',
  'departments.emergency': 'الطوارئ',
  'departments.pediatrics': 'طب الأطفال',
  'departments.cardiology': 'أمراض القلب',
  'departments.neurology': 'طب الأعصاب',
  'departments.orthopedics': 'العظام',
  'departments.radiology': 'الأشعة',
  'departments.laboratory': 'المختبر',
  'departments.pharmacy': 'الصيدلية',
  'departments.nursing': 'التمريض',
  'departments.administration': 'الإدارة',
  
  // Charts and Analytics - Arabic
  'reports.chart': 'الرسم البياني',
  'reports.showing': 'عرض',
  'reports.by': 'حسب',
  'reports.unsupportedChartType': 'نوع الرسم البياني غير مدعوم',
  'reports.loadingReport': 'تحميل التقرير...',
  'reports.noData': 'لا توجد بيانات',
  'reports.detailedData': 'البيانات التفصيلية',
  'reports.showingRecords': 'عرض {count} سجل',
  
  // Summary Statistics - Arabic
  'reports.totalUsers': 'إجمالي المستخدمين',
  'reports.activeUsers': 'المستخدمون النشطون',
  'reports.averageUptime': 'متوسط وقت التشغيل',
  'reports.totalErrors': 'إجمالي الأخطاء',
  'reports.totalNewPatients': 'إجمالي المرضى الجدد',
  'reports.totalVisits': 'إجمالي الزيارات',
  'reports.averageSatisfaction': 'متوسط الرضا',
  'reports.readmissionRate': 'معدل إعادة الدخول',
  'reports.totalRevenue': 'إجمالي الإيرادات',
  'reports.totalProfit': 'إجمالي الربح',
  'reports.profitMargin': 'هامش الربح',
  'reports.collectionRate': 'معدل التحصيل',
  'reports.totalStaff': 'إجمالي الموظفين',
  'reports.averageProductivity': 'متوسط الإنتاجية',
  'reports.trainingCompletion': 'إكمال التدريب',
  'reports.targetsMet': 'الأهداف المحققة',
  'reports.overallPerformance': 'الأداء العام',
  'reports.warningKPIs': 'مؤشرات تحذيرية',
  'reports.criticalKPIs': 'مؤشرات حرجة',
  
  // KPI Performance - Arabic
  'reports.kpiPerformance': 'أداء مؤشرات الأداء الرئيسية',
  
  // Financial Breakdown - Arabic
  'reports.revenueBreakdown': 'تفكيك الإيرادات',
  'reports.paymentMethods': 'طرق الدفع',
  
  // Financial Filters - Arabic
  'reports.financialFilters': 'مرشحات مالية',
  'reports.paymentMethod': 'طريقة الدفع',
  'reports.allMethods': 'جميع الطرق',
  'reports.revenueSource': 'مصدر الإيرادات',
  'reports.allSources': 'جميع المصادر',
  'reports.consultations': 'الاستشارات',
  'reports.procedures': 'الإجراءات',
  'reports.pharmacy': 'الصيدلية',
  'reports.laboratory': 'المختبر',
  'reports.radiology': 'الأشعة',
  'reports.amountRange': 'نطاق المبلغ',
  'reports.min': 'الحد الأدنى',
  'reports.max': 'الحد الأقصى',
  
  // Staff Filters - Arabic
  'reports.staffFilters': 'مرشحات الموظفين',
  'reports.employeeType': 'نوع الموظف',
  'reports.allEmployees': 'جميع الموظفين',
  'reports.fullTime': 'دوام كامل',
  'reports.partTime': 'دوام جزئي',
  'reports.contract': 'عقد مؤقت',
  'reports.consultant': 'استشاري',
  'reports.experience': 'الخبرة',
  'reports.allLevels': 'جميع المستويات',
  'reports.junior': 'مبتدئ',
  'reports.midLevel': 'متوسط',
  'reports.senior': 'كبير',
  'reports.expert': 'خبير',
  'reports.years': 'سنوات',
  'reports.shift': 'النوبة',
  'reports.allShifts': 'جميع النوبات',
  'reports.morningShift': 'نوبة صباحية',
  'reports.afternoonShift': 'نوبة مسائية',
  'reports.nightShift': 'نوبة ليلية',
  'reports.rotatingShift': 'نوبة متناوبة',

  // Clinical Research System - Arabic
  'research.clinicalResearch': 'البحوث السريرية',
  'research.comprehensiveResearchManagement': 'إدارة شاملة للبحوث السريرية',
  'research.dashboard': 'لوحة التحكم',
  'research.studies': 'الدراسات',
  'research.participants': 'المشاركون',
  'research.data': 'البيانات',
  'research.protocols': 'البروتوكولات',
  'research.regulatory': 'التنظيمي',
  'research.adverseEvents': 'الأحداث الضائرة',
  'research.documents': 'الوثائق',
  'research.analytics': 'التحليلات',
  
  // Dashboard Metrics - Arabic
  'research.totalStudies': 'إجمالي الدراسات',
  'research.activeStudies': 'الدراسات النشطة',
  'research.totalParticipants': 'إجمالي المشاركين',
  'research.enrollmentRate': 'معدل التسجيل',
  'research.completionRate': 'معدل الإنجاز',
  'research.fromLastYear': 'من العام الماضي',
  'research.recruiting': 'التوظيف',
  'research.active': 'نشط',
  'research.thisMonth': 'هذا الشهر',
  'research.aboveTarget': 'فوق المستهدف',
  
  // Study Management - Arabic
  'research.studiesOverview': 'نظرة عامة على الدراسات',
  'research.manageAllClinicalStudies': 'إدارة جميع الدراسات السريرية',
  'research.newStudy': 'دراسة جديدة',
  'research.searchStudies': 'البحث في الدراسات',
  'research.allStatuses': 'جميع الحالات',
  'research.allPhases': 'جميع المراحل',
  'research.studyTitle': 'عنوان الدراسة',
  'research.phase': 'المرحلة',
  'research.status': 'الحالة',
  'research.therapeuticArea': 'المجال العلاجي',
  'research.principalInvestigator': 'الباحث الرئيسي',
  'research.enrollment': 'التسجيل',
  'research.timeline': 'الجدول الزمني',
  'research.planning': 'التخطيط',
  'research.completed': 'مكتمل',
  'research.suspended': 'معلق',
  'research.terminated': 'منتهي',
  
  // Study Creation - Arabic
  'research.createNewStudy': 'إنشاء دراسة جديدة',
  'research.fillOutStudyDetails': 'املأ تفاصيل الدراسة',
  'research.basicInfo': 'المعلومات الأساسية',
  'research.studyDesign': 'تصميم الدراسة',
  'research.criteria': 'المعايير',
  'research.enterStudyTitle': 'أدخل عنوان الدراسة',
  'research.selectPhase': 'اختر المرحلة',
  'research.enterStudyDescription': 'أدخل وصف الدراسة',
  'research.selectTherapeuticArea': 'اختر المجال العلاجي',
  'research.selectStudyType': 'اختر نوع الدراسة',
  'research.enterPIName': 'أدخل اسم الباحث الرئيسي',
  'research.enterSponsorName': 'أدخل اسم الراعي',
  'research.targetEnrollment': 'الهدف من التسجيل',
  'research.startDate': 'تاريخ البدء',
  'research.estimatedEndDate': 'تاريخ الانتهاء المتوقع',
  'research.objectives': 'الأهداف',
  'research.enterStudyObjectives': 'أدخل أهداف الدراسة',
  'research.inclusionCriteria': 'معايير الإدراج',
  'research.enterInclusionCriteria': 'أدخل معايير الإدراج',
  'research.exclusionCriteria': 'معايير الاستبعاد',
  'research.enterExclusionCriteria': 'أدخل معايير الاستبعاد',
  'research.createStudy': 'إنشاء الدراسة',
  
  // Participant Management - Arabic
  'research.participantRegistry': 'سجل المشاركين',
  'research.manageAllParticipants': 'إدارة جميع المشاركين',
  'research.enrollParticipant': 'تسجيل مشارك',
  'research.searchParticipants': 'البحث في المشاركين',
  'research.allStudies': 'جميع الدراسات',
  'research.participantId': 'معرف المشارك',
  'research.study': 'الدراسة',
  'research.demographics': 'الديموجرافيا',
  'research.compliance': 'الامتثال',
  'research.nextVisit': 'الزيارة التالية',
  'research.screening': 'الفحص',
  'research.enrolled': 'مسجل',
  'research.withdrawn': 'منسحب',
  'research.discontinued': 'متوقف',
  'research.avgCompliance': 'متوسط الامتثال',
  
  // Participant Enrollment - Arabic
  'research.enrollNewParticipant': 'تسجيل مشارك جديد',
  'research.completeParticipantInformation': 'أكمل معلومات المشارك',
  'research.contact': 'الاتصال',
  'research.medical': 'الطبي',
  'research.consent': 'الموافقة',
  'research.selectStudy': 'اختر الدراسة',
  'research.firstName': 'الاسم الأول',
  'research.lastName': 'الاسم الأخير',
  'research.dateOfBirth': 'تاريخ الميلاد',
  'research.gender': 'الجنس',
  'research.selectGender': 'اختر الجنس',
  'research.male': 'ذكر',
  'research.female': 'أنثى',
  'research.other': 'آخر',
  'research.ethnicity': 'العرق',
  'research.selectEthnicity': 'اختر العرق',
  'research.phone': 'الهاتف',
  'research.email': 'البريد الإلكتروني',
  'research.address': 'العنوان',
  'research.emergencyContact': 'جهة الاتصال للطوارئ',
  'research.emergencyPhone': 'هاتف الطوارئ',
  'research.medicalHistory': 'التاريخ الطبي',
  'research.enterMedicalHistory': 'أدخل التاريخ الطبي',
  'research.currentMedications': 'الأدوية الحالية',
  'research.enterCurrentMedications': 'أدخل الأدوية الحالية',
  'research.allergies': 'الحساسية',
  'research.enterAllergies': 'أدخل الحساسية',
  'research.consentDate': 'تاريخ الموافقة',
  'research.consentChecklist': 'قائمة الموافقة',
  'research.randomizationGroup': 'مجموعة العشوائية',
  'research.selectGroup': 'اختر المجموعة',
  'research.treatmentGroup': 'مجموعة العلاج',
  'research.controlGroup': 'المجموعة الضابطة',
  'research.placeboGroup': 'مجموعة الدواء الوهمي',
  
  // Data Collection - Arabic
  'research.dataCollectionForms': 'نماذج جمع البيانات',
  'research.manageFormsAndDataEntry': 'إدارة النماذج وإدخال البيانات',
  'research.createForm': 'إنشاء نموذج',
  'research.formName': 'اسم النموذج',
  'research.version': 'الإصدار',
  'research.lastModified': 'آخر تعدي��',
  'research.dataEntry': 'إدخال البيانات',
  'research.forms': 'النماذج',
  'research.dataEntryForm': 'نموذج إدخال البيانات',
  'research.baselineAssessmentForm': 'نموذج التقييم الأساسي',
  'research.selectParticipant': 'اختر المشارك',
  'research.visitDate': 'تاريخ الزيارة',
  'research.vitalSigns': 'العلامات الحيوية',
  'research.bloodPressure': 'ضغط الدم',
  'research.heartRate': 'معدل ضربات القلب',
  'research.temperature': 'درجة الحرارة',
  'research.weight': 'الوزن',
  'research.symptoms': 'الأعراض',
  'research.notes': 'الملاحظات',
  'research.enterAdditionalNotes': 'أدخل ملاحظات إضافية',
  'research.continue': 'متابعة',
  'research.saveAndFinalize': 'حفظ وإنهاء',
  
  // Protocols - Arabic
  'research.studyProtocols': 'بروتوكولات الدراسة',
  'research.manageProtocolsAndAmendments': 'إدارة البروتوكولات والتعديلات',
  'research.newProtocol': 'بروتوكول جديد',
  'research.protocolTitle': 'عنوان البروتوكول',
  'research.author': 'المؤلف',
  'research.amendments': 'التعديلات',
  'research.protocolAmendments': 'تعديلات البروتوكول',
  'research.trackProtocolChanges': 'تتبع تغييرات البروتوكول',
  'research.newAmendment': 'تعديل جديد',
  'research.amendmentTitle': 'عنوان التعديل',
  'research.protocol': 'البروتوكول',
  'research.number': 'الرقم',
  'research.submittedDate': 'تاريخ التقديم',
  'research.templates': 'القوالب',
  'research.downloads': 'التحميلات',
  'research.updated': 'محدث',
  'research.download': 'تحميل',
  
  // Regulatory Compliance - Arabic
  'research.regulatoryApprovals': 'الموافقات التنظيمية',
  'research.trackAllRegulatoryApprovals': 'تتبع جميع الموافقات التنظيمية',
  'research.submitApproval': 'تقديم موافقة',
  'research.approvalType': 'نوع الموافقة',
  'research.authority': 'السلطة',
  'research.approvalNumber': 'رقم الموافقة',
  'research.validity': 'الصلاحية',
  'research.inspectionsAudits': 'التفتيش والمراجعة',
  'research.trackInspectionsAndAudits': 'تتبع التفتيش والمراجعة',
  'research.scheduleInspection': 'جدولة التفتيش',
  'research.inspectionType': 'نوع التفتيش',
  'research.inspector': 'المفتش',
  'research.date': 'التاريخ',
  'research.findings': 'النتائج',
  'research.outcome': 'النتيجة',
  'research.approvals': 'الموافقات',
  'research.inspections': 'التفتيش',
  'research.complianceOverview': 'نظرة عامة على الامتثال',
  'research.overallCompliance': 'الامتثال العام',
  'research.activeApprovals': 'الموافقات النشطة',
  'research.expiringWithin30Days': 'تنتهي خلال 30 يوماً',
  'research.upcomingDeadlines': 'المواعيد النهائية القادمة',
  'research.recentActivity': 'النشاط الحديث',
  
  // Adverse Events - Arabic
  'research.trackAndManageAdverseEvents': 'تتبع وإدارة الأحداث الضائرة',
  'research.reportAE': 'الإبلاغ عن حدث ضار',
  'research.eventTerm': 'مصطلح الحدث',
  'research.participant': 'المشارك',
  'research.severity': 'الشدة',
  'research.relationship': 'العلاقة',
  'research.onsetDate': 'تاريخ البداية',
  'research.events': 'الأحداث',
  'research.followUp': 'المتابعة',
  'research.serious': 'خطير',
  'research.expedited': 'عاجل',
  'research.mild': 'خفيف',
  'research.moderate': 'متوسط',
  'research.severe': 'شديد',
  'research.unrelated': 'غير مرتبط',
  'research.unlikely': 'غير محتمل',
  'research.possible': 'م��تمل',
  'research.probable': 'مرجح',
  'research.related': 'مرتبط',
  'research.ongoing': 'مستمر',
  'research.resolved': 'محلول',
  'research.followUpRequired': 'المتابعة مطلوبة',
  'research.adverseEventsRequiringFollowUp': 'الأحداث الضائرة التي تتطلب متابعة',
  'research.updateFollowUp': 'تحديث المتابعة',
  'research.reportAdverseEvent': 'الإبلاغ عن حدث ضار',
  'research.completeAEReportForm': 'أكمل نموذج الإبلاغ عن الحدث الضار',
  'research.eventDetails': 'تفاصيل الحدث',
  'research.assessment': 'التقييم',
  'research.enterEventTerm': 'أدخل مصطلح الحدث',
  'research.describeEvent': 'وصف الحدث',
  'research.seriousness': 'الخطورة',
  'research.nonSerious': 'غير خطير',
  'research.actionsTaken': 'الإجراءات المتخذة',
  'research.describeActionsTaken': 'وصف الإجراءات المتخذة',
  'research.relationshipToStudyDrug': 'العلاقة بدواء الدراسة',
  'research.expectedness': 'التوقع',
  'research.expected': 'متوقع',
  'research.unexpected': 'غير متوقع',
  'research.reporterAssessment': 'تقييم المبلغ',
  'research.provideAssessment': 'قدم التقييم',
  'research.submitReport': 'تقديم التقرير',
  
  // Document Management - Arabic
  'research.documentLibrary': 'مكتبة الوثائق',
  'research.manageAllStudyDocuments': 'إدارة جميع وثائق الدراسة',
  'research.uploadDocument': 'رفع وثيقة',
  'research.searchDocuments': 'البحث في الوثائق',
  'research.documentType': 'نوع الوثيقة',
  'research.allTypes': 'جميع الأنواع',
  'research.consentForms': 'نماذج الموافقة',
  'research.casereportForms': 'نماذج تقرير الحالة',
  'research.brochures': 'الكتيبات',
  'research.documentName': 'اسم الوثيقة',
  'research.type': 'النوع',
  'research.uploadDate': 'تاريخ الرفع',
  'research.size': 'الحجم',
  'research.library': 'المكتبة',
  'research.categories': 'الفئات',
  'research.versions': 'الإصدارات',
  'research.documentVersions': 'إصدارات الوثيقة',
  'research.trackDocumentVersionHistory': 'تتبع تاريخ إصدارات الوثيقة',
  'research.viewAll': 'عرض الكل',
  'research.draft': 'مسودة',
  'research.approved': 'موافق عليه',
  'research.expired': 'منتهي الصلاحية',
  'research.archived': 'مؤرشف',
  'research.under_review': 'قيد المراجعة',
  'research.rejected': 'مرفوض',
  
  // Analytics and Reports - Arabic
  'research.researchAnalytics': 'تحليلات البحوث',
  'research.comprehensiveAnalyticsAndInsights': 'تحليلات ورؤى شاملة',
  'research.exportAnalytics': 'تصدير التحليلات',
  'research.enrollment': 'التسجيل',
  'research.performance': 'الأداء',
  'research.enrollmentTrend': 'اتجاه التسجيل',
  'research.monthlyEnrollmentVsTarget': 'التسجيل الشهري مقابل المستهدف',
  'research.target': 'المستهدف',
  'research.actual': 'الفعلي',
  'research.cumulativeEnrollment': 'التسجيل التراكمي',
  'research.totalEnrollmentOverTime': 'إجمالي التسجيل عبر الزمن',
  'research.studyProgress': 'تقدم الدراسة',
  'research.enrollmentProgressByStudy': 'تقدم التسجيل حسب الدراسة',
  'research.visitCompliance': 'امتثال الزيارات',
  'research.visitComplianceByStudy': 'امتثال الزيارات حسب الدراسة',
  'research.protocolDeviations': 'انحرافات البروتوكول',
  'research.monthlyDeviationTrend': 'اتجاه الانحرافات الشهرية',
  'research.reported': 'مبلغ عنه',
  'research.complianceMetrics': 'مقاييس الامتثال',
  'research.keyComplianceIndicators': 'مؤشرات الامتثال الرئيسية',
  'research.activeDeviations': 'الانحرافات النشطة',
  'research.avgResolutionDays': 'متوسط أيام الحل',
  'research.dataCompleteness': 'اكتمال البيانات',
  'research.studyTimeline': 'الجدول الزمني للدراسة',
  'research.keyMilestonesAndDeadlines': 'المعالم الرئيسية والمواعيد النهائية',
  'research.planned': 'مخطط',
  'research.upcoming': 'قادم',
  'research.onTime': 'في الوقت المحدد',
  'research.delayed': 'متأخر',
  'research.patientsPerMonth': 'مرضى شهرياً',
  'research.participantRetention': 'الاحتفاظ بالمشاركين',
  'research.dataAccuracy': 'دقة البيانات',
  'research.sitePerformance': 'أداء الموقع',
  'research.performanceByStudySite': 'الأداء حسب موقع الدراسة',
  'research.recruitmentSources': 'مصادر التوظيف',
  'research.enrollmentBySource': 'التسجيل حسب المصدر',
  
  // Additional Terms - Arabic
  'research.overview': 'نظرة عامة',

  // Appointments System - Arabic
  'appointments.management': 'إدارة المواعيد',
  'appointments.overview': 'نظرة عامة',
  'appointments.schedule': 'جدولة موعد',
  'appointments.today': 'اليوم',
  'appointments.waitingList': 'قائمة الانتظار',
  'appointments.allAppointments': 'جميع المواعيد',
  'appointments.scheduleDescription': 'جدولة موعد جديد للمريض',
  'appointments.todaysAppointments': 'مواعيد اليوم',
  'appointments.realTimeQueue': 'طابور مباشر',
  'appointments.lastUpdated': 'آخر تحديث',
  'appointments.autoRefresh': 'تحديث تلقائي',
  'appointments.addToQueue': 'إضافة للطابور',
  'appointments.totalWaiting': 'إجمالي المنتظرين',
  'appointments.waiting': 'في الانتظار',
  'appointments.called': 'تم الاستدعاء',
  'appointments.noResponse': 'لا إجابة',
  'appointments.avgWait': 'متوسط الانتظار',
  'appointments.searchWaitingList': 'البحث في قائمة الانتظار',
  'appointments.sortBy': 'ترتيب حسب',
  'appointments.position': 'الموضع',
  'appointments.waitTime': 'وقت الانتظار',
  'appointments.addedTime': 'وقت الإضافة',
  'appointments.noWaitingPatients': 'لا يوجد مرضى في الانتظار',
  'appointments.waitingListEmpty': 'قائمة الانتظار فارغة',
  'appointments.call': 'استدعاء',
  'appointments.recall': 'إعادة استدعاء',
  'appointments.seen': 'تم الفحص',
  'appointments.patientDetails': 'تفاصيل المريض',
  'appointments.currentPatient': 'المريض الحالي',
  'appointments.estimatedWait': 'الانتظار المتوقع',
  'appointments.triageNotes': 'ملاحظات الفرز',
  'appointments.timeline': 'الجدول الزمني',
  'appointments.addedToQueue': 'تمت إضافته للطابور',
  'appointments.remindersSent': 'تم إرسال التذكيرات',
  'appointments.addToQueueDescription': 'إضافة مريض جديد لقائمة الانتظار',
  'appointments.addToQueueComingSoon': 'قريباً - إضافة مريض لقائمة الانتظار',

  // Appointment Scheduling Steps - Arabic
  'appointments.step.patient': 'المريض',
  'appointments.step.doctor': 'الطبيب',
  'appointments.step.datetime': 'التاريخ والوقت',
  'appointments.step.details': 'التفاصيل',
  'appointments.step.confirm': 'التأكيد',

  // Patient Selection - Arabic
  'appointments.existingPatient': 'مريض موجود',
  'appointments.newPatient': 'مريض جديد',
  'appointments.searchPatients': 'البحث عن المرضى...',

  // Doctor Selection - Arabic
  'appointments.searchDoctors': 'البحث عن الأطباء...',
  'appointments.yearsExp': 'سنوات خبرة',
  'appointments.consultationFee': 'رسوم الاستشارة',
  'appointments.daysAvailable': 'أيام متاحة',

  // Date and Time Selection - Arabic
  'appointments.selectDate': 'اختيار التاريخ',
  'appointments.selectTime': 'اختيار الوقت',

  // Appointment Types - Arabic
  'appointments.consultation': 'استشارة',
  'appointments.followUp': 'متابعة',
  'appointments.procedure': 'إجراء',
  'appointments.emergency': 'طوارئ',
  'appointments.selectType': 'اختيار النوع',

  // Appointment Details - Arabic
  'appointments.reasonPlaceholder': 'اكتب سبب الزيارة...',
  'appointments.symptomsPlaceholder': 'اكتب الأعراض المصاحبة...',
  'appointments.notesPlaceholder': 'ملاحظات إضافية...',
  'appointments.location': 'الموقع',
  'appointments.selectLocation': 'اختيار الموقع',
  'appointments.clinic': 'عيادة',
  'appointments.emergencyRoom': 'غرفة الطوارئ',

  // Appointment Confirmation - Arabic
  'appointments.confirmAppointment': 'تأكيد الموعد',
  'appointments.confirmDescription': 'يرجى مراجعة تفاصيل الموعد قبل التأكيد',
  'appointments.importantInfo': 'معلومات مهمة',
  'appointments.arriveEarly': 'الحضو�� قبل 15 دقيقة من الموعد',
  'appointments.bringDocuments': 'إحضار الوثائق الطبية والهوية',
  'appointments.confirmationSent': 'سيتم إرسال رسالة تأكيد',
  'appointments.scheduleAppointment': 'جدولة الموعد',

  // Appointment Status - Arabic
  'appointments.scheduled': 'مجدول',
  'appointments.confirmed': 'مؤكد',
  'appointments.checkedIn': 'تم الوصول',
  'appointments.inProgress': 'جاري الفحص',
  'appointments.completed': 'مكتمل',
  'appointments.cancelled': 'ملغي',
  'appointments.noShow': 'لم يحضر',
  'appointments.checkIn': 'تسجيل الوصول',
  'appointments.start': 'بدء الفحص',
  'appointments.complete': 'إكمال',
  'appointments.started': 'بدء',
  'appointments.checked': 'تم التحقق',

  // Today's Appointments - Arabic
  'appointments.noAppointmentsToday': 'لا توجد مواعيد اليوم',
  'appointments.noAppointmentsTodayDescription': 'لم يتم جدولة أي مواعيد لهذا اليوم',
  'appointments.appointmentDetails': 'تفاصيل الموعد',
  'appointments.updateAppointment': 'تحديث الموعد',
  'appointments.updateDescription': 'تحديث حالة أو ملاحظات الموعد',
  'appointments.updateNotesPlaceholder': 'ملا��ظات التحديث...',

  // Statistics and Overview - Arabic
  'appointments.todayTotal': 'إجمالي اليوم',
  'appointments.pending': 'معلقة',
  'appointments.doctorsAvailable': 'أطباء متاحون',
  'appointments.quickActions': 'إجراءات سريعة',
  'appointments.quickActionsDescription': 'أكثر الإجراءات استخداماً',
  'appointments.scheduleNew': 'جدولة موعد جديد',
  'appointments.viewToday': 'عرض مواعيد اليوم',
  'appointments.manageQueue': 'إدارة قائمة الانتظار',
  'appointments.searchAll': 'البحث في جميع المواعيد',
  'appointments.recentActivity': 'النشاط الحديث',
  'appointments.recentActivityDescription': 'أحدث الأنشطة في نظام المواعيد',
  'appointments.todaySchedule': 'جدول اليوم',
  'appointments.upcomingAppointments': 'المواعيد القادمة',
  'appointments.viewAllToday': 'عرض جميع مواعيد اليوم',

  // List Views - Arabic
  'appointments.listView': 'عرض قائمة',
  'appointments.timelineView': 'عرض زمني',

  // Communication - Arabic
  'appointments.sendSMS': 'إرسال رسالة نصية',
  'appointments.makeCall': 'إجراء مكالمة',
  'appointments.reminders': 'تذكيرات',

  // Vitals - Arabic
  'appointments.vitals': 'العلامات الحيوية',
  'appointments.bloodPressure': 'ضغط الدم',
  'appointments.heartRate': 'نبضات القلب',

  // Walk-in Types - Arabic
  'appointments.walk-in': 'مراجع بدون موعد',
  'appointments.urgent-referral': 'إحالة عاجلة',

  // Common Actions - Arabic
  'common.scheduling': 'جاري الجدولة...',
  'common.years': 'سنوات',
  'common.male': 'ذكر',
  'common.female': 'أنثى'امة',
  'research.quickActions': 'إجراءات سريعة',
  'research.alertsNotifications': 'التنبيهات والإشعارات',
  'research.protocolDeviation': 'انحراف البروتوكول',
  'research.upcomingVisits': 'الزيارات القادمة',
  'research.milestoneReached': 'تم الوصول للمعلم',
  'research.exportData': 'تصدير البيانات',
  'research.studyStatusDistribution': 'توزيع حالة الدراسة',
  'research.currentStudyStatuses': 'حالات الدراسة الحالية',
  'research.recentStudies': 'الدراسات الحديثة',
  'research.overviewOfCurrentStudies': 'نظرة عامة على الدراسات الحالية',
  'research.end': 'النهاية',
  'research.start': 'البداية',
  'research.timelineViewOfAllStudies': 'عرض الجدول الزمني لجميع الدراسات',
  'research.studiesByPhase': 'الدراسات حسب المرحلة',
  'research.studiesByStatus': 'الدراسات حسب الحالة',
  'research.enrollmentProgress': 'تقدم التسجيل',
  'research.genderDistribution': 'توزيع الجنس',
  'research.ageGroups': 'الفئات العمرية',
  'research.visitSchedule': 'جدول الزيارات',
  'research.upcomingVisitsAndScheduling': 'الزيارات القادمة والجدولة',
  'research.visitSchedulingFeature': 'ميزة جدولة الزيارات',
  'research.participantDetails': 'تفاصيل المشارك',
  'research.daysEnrolled': 'أيام التسجيل',
  'research.contactInformation': 'معلومات الاتصال',
  'research.studyInformation': 'معلومات الدراسة',
  'research.enrollmentDate': 'تاريخ التسجيل',
  'research.lastVisit': 'آخر زيارة',
  'research.basicDemographics': 'الديموجرافيا الأساسية',
  'research.age': 'العمر',
  'research.physicalMeasurements': 'القياسات الجسدية',
  'research.height': 'الطول',
  'research.visitHistoryAndScheduling': 'تاريخ الزيارات والجدولة',
  'research.concomitantMedications': 'الأدوية المصاحبة',
  'research.formProgress': 'تقدم النموذج',
  'research.completion': 'الإنجاز',
  'research.labResults': 'نتائج المختبر',
  'research.dataValidation': 'التحقق من البيانات',
  'research.valueOutOfRange': 'قيمة خارج النطاق',
  'research.dataValid': 'البيانات صحيحة',
  'research.dataQuality': 'جودة البيانات',
  'research.missingValues': 'القيم المفقودة',
  'research.outOfRange': 'خارج النطاق',
  'research.duplicates': 'المكررات',
  'research.aeBySeverity': 'الأحداث الضائرة حسب الشدة',
  'research.aeByRelationship': 'الأحداث الضائرة حسب العلاقة',
  'research.reportingTimeline': 'الجدول الزمني للإبلاغ',
  'research.timelyReporting': 'الإبلاغ في الوقت المناسب',
  'research.within24Hours': 'خلال 24 ساعة',
  'research.within7Days': 'خلال 7 أيام',
  'research.eventDescription': 'وصف الحدث',
  'research.resolving': 'في طور الحل',
  'research.sequelae': 'عواقب',
  'research.fatal': 'مميت',
  'research.completionRate': 'معدل الإنجاز',
};

// Function to merge with existing translations
export const getArabicExtensions = () => arabicLabExtensions;