// Extended translations for new pages and features
export const extendedTranslations = {
  en: {
    // Landing Page
    'landing.brandName': 'MediCore',
    'landing.tagline': 'Complete Healthcare Management',
    'landing.nav.pricing': 'Pricing',
    'landing.nav.features': 'Features',
    'landing.nav.about': 'About',
    'landing.nav.contact': 'Contact',
    'landing.nav.login': 'Login',
    'landing.nav.getStarted': 'Get Started',
    'landing.hero.badge': 'Trusted by 500+ Healthcare Institutions',
    'landing.hero.title': 'Transform Your Healthcare Management',
    'landing.hero.subtitle': 'Streamline operations, improve patient care, and boost efficiency with our comprehensive hospital management system.',
    'landing.hero.cta': 'Start Free Trial',
    'landing.hero.watchDemo': 'Watch Demo',
    'landing.stats.hospitals': 'Hospitals',
    'landing.stats.healthcare': 'Healthcare Professionals',
    'landing.stats.patients': 'Patients Served',
    'landing.stats.uptime': 'System Uptime',
    'landing.features.title': 'Comprehensive Healthcare Solutions',
    'landing.features.subtitle': 'Everything you need to manage your healthcare facility efficiently',
    'landing.features.patientCare.title': 'Patient Care Excellence',
    'landing.features.patientCare.desc': 'Complete patient management with electronic health records, appointment scheduling, and care coordination.',
    'landing.features.scheduling.title': 'Smart Scheduling',
    'landing.features.scheduling.desc': 'Intelligent appointment booking system with automated reminders and real-time availability.',
    'landing.features.emr.title': 'Electronic Medical Records',
    'landing.features.emr.desc': 'Secure, comprehensive digital health records with instant access and seamless sharing.',
    'landing.features.analytics.title': 'Advanced Analytics',
    'landing.features.analytics.desc': 'Powerful reporting and analytics to optimize operations and improve patient outcomes.',
    'landing.features.security.title': 'Enterprise Security',
    'landing.features.security.desc': 'HIPAA-compliant security with encryption, audit trails, and access controls.',
    'landing.features.collaboration.title': 'Team Collaboration',
    'landing.features.collaboration.desc': 'Seamless communication and collaboration tools for healthcare teams.',
    'landing.testimonials.title': 'Trusted by Healthcare Leaders',
    'landing.testimonials.subtitle': 'See what our customers have to say',
    'landing.cta.title': 'Ready to Transform Your Healthcare Facility?',
    'landing.cta.subtitle': 'Join thousands of healthcare professionals who trust MediCore for their daily operations.',
    'landing.cta.register': 'Start Free Trial',
    'landing.cta.viewPricing': 'View Pricing',
    'landing.footer.description': 'Empowering healthcare facilities with comprehensive management solutions.',
    'landing.footer.product': 'Product',
    'landing.footer.company': 'Company',
    'landing.footer.legal': 'Legal',
    'landing.footer.integrations': 'Integrations',
    'landing.footer.api': 'API',
    'landing.footer.about': 'About Us',
    'landing.footer.careers': 'Careers',
    'landing.footer.contact': 'Contact',
    'landing.footer.blog': 'Blog',
    'landing.footer.privacy': 'Privacy Policy',
    'landing.footer.terms': 'Terms of Service',
    'landing.footer.security': 'Security',
    'landing.footer.compliance': 'Compliance',
    'landing.footer.rights': 'All rights reserved.',
    'landing.footer.global': 'Global Coverage',
    'landing.footer.secure': 'Secure & Compliant',

    // Registration Page
    'register.title': 'Create Your Account',
    'register.subtitle': 'Join thousands of healthcare professionals',
    'register.step1Title': 'Personal Information',
    'register.step1Desc': 'Enter your basic details',
    'register.step2Title': 'Select Your Role',
    'register.step2Desc': 'Choose your professional role',
    'register.step3Title': 'Professional Details',
    'register.step3Desc': 'Complete your professional profile',
    'register.firstName': 'First Name',
    'register.lastName': 'Last Name',
    'register.email': 'Email Address',
    'register.phone': 'Phone Number',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm Password',
    'register.passwordMismatch': 'Passwords do not match',
    'register.selectRole': 'Select Your Professional Role',
    'register.roleHelp': 'Choose the role that best describes your position',
    'register.categories.management': 'Management',
    'register.categories.medical': 'Medical',
    'register.categories.technical': 'Technical',
    'register.categories.administration': 'Administration',
    'register.roleDescriptions.admin': 'System administration and overall management',
    'register.roleDescriptions.doctor': 'Medical consultations and patient care',
    'register.roleDescriptions.nurse': 'Patient care and medical assistance',
    'register.roleDescriptions.receptionist': 'Patient registration and appointment management',
    'register.roleDescriptions.lab_tech': 'Laboratory tests and sample analysis',
    'register.roleDescriptions.pharmacist': 'Medication management and dispensing',
    'register.roleDescriptions.radiologist': 'Medical imaging and diagnostic services',
    'register.specialization': 'Specialization',
    'register.selectSpecialization': 'Select your specialization',
    'register.licenseNumber': 'License Number',
    'register.experience': 'Years of Experience',
    'register.selectExperience': 'Select experience level',
    'register.experience01': '0-1 years',
    'register.experience25': '2-5 years',
    'register.experience610': '6-10 years',
    'register.experience10plus': '10+ years',
    'register.department': 'Department',
    'register.notes': 'Additional Notes',
    'register.notesPlaceholder': 'Any additional information or special requirements',
    'register.createAccount': 'Create Account',
    'register.backToLogin': 'Back to Login',
    'register.error': 'Registration failed. Please try again.',

    // Specializations
    'specializations.general_practice': 'General Practice',
    'specializations.internal_medicine': 'Internal Medicine',
    'specializations.cardiology': 'Cardiology',
    'specializations.neurology': 'Neurology',
    'specializations.orthopedics': 'Orthopedics',
    'specializations.dermatology': 'Dermatology',
    'specializations.pediatrics': 'Pediatrics',
    'specializations.gynecology': 'Gynecology',
    'specializations.surgery': 'Surgery',
    'specializations.general_nursing': 'General Nursing',
    'specializations.icu_nursing': 'ICU Nursing',
    'specializations.er_nursing': 'Emergency Nursing',
    'specializations.surgical_nursing': 'Surgical Nursing',
    'specializations.pediatric_nursing': 'Pediatric Nursing',
    'specializations.geriatric_nursing': 'Geriatric Nursing',
    'specializations.clinical_chemistry': 'Clinical Chemistry',
    'specializations.hematology': 'Hematology',
    'specializations.microbiology': 'Microbiology',
    'specializations.pathology': 'Pathology',
    'specializations.diagnostic_radiology': 'Diagnostic Radiology',
    'specializations.interventional_radiology': 'Interventional Radiology',
    'specializations.nuclear_medicine': 'Nuclear Medicine',

    // Auth Extensions
    'auth.noAccount': "Don't have an account?",
    'auth.createAccount': 'Create Account',
    'auth.backToHome': 'Back to Home',
    'auth.pricing': 'Pricing',
    'auth.privacy': 'Privacy Policy',
    'auth.terms': 'Terms of Service',

    // Pricing Page
    'pricing.title': 'Choose Your Plan',
    'pricing.hero.title': 'Simple, Transparent Pricing',
    'pricing.hero.subtitle': 'Choose the perfect plan for your healthcare facility. All plans include our core features with no hidden fees.',
    'pricing.billing.monthly': 'Monthly',
    'pricing.billing.yearly': 'Yearly',
    'pricing.billing.save': 'Save',
    'pricing.billing.month': 'month',
    'pricing.billing.year': 'year',
    'pricing.billing.billed': 'billed',
    'pricing.badges.popular': 'Most Popular',
    'pricing.badges.advanced': 'Advanced',
    'pricing.plans.starter.name': 'Starter',
    'pricing.plans.starter.desc': 'Perfect for small clinics and practices',
    'pricing.plans.professional.name': 'Professional',
    'pricing.plans.professional.desc': 'Ideal for medium-sized hospitals',
    'pricing.plans.enterprise.name': 'Enterprise',
    'pricing.plans.enterprise.desc': 'Built for large healthcare systems',
    'pricing.features.patients50': 'Up to 50 patients',
    'pricing.features.patients500': 'Up to 500 patients',
    'pricing.features.patientsUnlimited': 'Unlimited patients',
    'pricing.features.basicEMR': 'Basic EMR system',
    'pricing.features.advancedEMR': 'Advanced EMR with templates',
    'pricing.features.fullEMR': 'Full EMR with AI assistance',
    'pricing.features.appointments': 'Appointment scheduling',
    'pricing.features.labIntegration': 'Laboratory integration',
    'pricing.features.pharmacyManagement': 'Pharmacy management',
    'pricing.features.allIntegrations': 'All system integrations',
    'pricing.features.basicReports': 'Basic reporting',
    'pricing.features.advancedReports': 'Advanced analytics & reports',
    'pricing.features.emailSupport': 'Email support',
    'pricing.features.prioritySupport': 'Priority support',
    'pricing.features.dedicatedSupport': '24/7 dedicated support',
    'pricing.features.mobileApp': 'Mobile app access',
    'pricing.features.dataBackup': 'Daily data backup',
    'pricing.features.customBranding': 'Custom branding',
    'pricing.features.apiAccess': 'API access',
    'pricing.features.multiLocation': 'Multi-location support',
    'pricing.features.aiAssistant': 'AI diagnostic assistant',
    'pricing.features.customDevelopment': 'Custom development',
    'pricing.features.onPremise': 'On-premise deployment',
    'pricing.features.sla99': '99.9% SLA guarantee',
    'pricing.features.training': 'Staff training included',
    'pricing.features.compliance': 'Full compliance suite',
    'pricing.limitations.limitedIntegrations': 'Limited integrations',
    'pricing.limitations.basicCustomization': 'Basic customization only',
    'pricing.getStarted': 'Get Started',
    'pricing.addons.title': 'Powerful Add-ons',
    'pricing.addons.subtitle': 'Extend your system with specialized modules',
    'pricing.addons.telemedicine.name': 'Telemedicine Module',
    'pricing.addons.telemedicine.desc': 'Video consultations and remote patient monitoring',
    'pricing.addons.analytics.name': 'Advanced Analytics',
    'pricing.addons.analytics.desc': 'AI-powered insights and predictive analytics',
    'pricing.addons.hipaa.name': 'HIPAA Compliance Suite',
    'pricing.addons.hipaa.desc': 'Enhanced security and compliance tools',
    'pricing.addons.add': 'Add',
    'pricing.faqs.title': 'Frequently Asked Questions',
    'pricing.faqs.subtitle': 'Everything you need to know about our pricing',
    'pricing.faqs.trialPeriod.question': 'Do you offer a free trial?',
    'pricing.faqs.trialPeriod.answer': 'Yes, we offer a 30-day free trial for all plans. No credit card required.',
    'pricing.faqs.dataExport.question': 'Can I export my data?',
    'pricing.faqs.dataExport.answer': 'Absolutely. You can export all your data at any time in standard formats.',
    'pricing.faqs.setup.question': 'Is there a setup fee?',
    'pricing.faqs.setup.answer': 'No setup fees for any plan. We provide free onboarding and training.',
    'pricing.faqs.support.question': 'What support do you provide?',
    'pricing.faqs.support.answer': 'We offer email, phone, and chat support. Enterprise customers get dedicated support.',
    'pricing.faqs.customization.question': 'Can the system be customized?',
    'pricing.faqs.customization.answer': 'Yes, we offer various levels of customization based on your plan.',
    'pricing.enterprise.title': 'Need a Custom Solution?',
    'pricing.enterprise.subtitle': 'Contact us for enterprise pricing and custom implementations',
    'pricing.enterprise.contact': 'Contact Sales',
    'pricing.enterprise.demo': 'Schedule Demo',

    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.hero.title': 'Your Privacy is Our Priority',
    'privacy.hero.subtitle': 'We are committed to protecting your personal information and being transparent about how we collect, use, and share your data.',
    'privacy.lastUpdated': 'Last updated',
    'privacy.version': 'Version',
    'privacy.tableOfContents': 'Table of Contents',
    'privacy.highlights.hipaa.title': 'HIPAA Compliant',
    'privacy.highlights.hipaa.desc': 'Full compliance with healthcare privacy regulations',
    'privacy.highlights.encryption.title': 'End-to-End Encryption',
    'privacy.highlights.encryption.desc': 'Your data is encrypted at rest and in transit',
    'privacy.highlights.transparency.title': 'Complete Transparency',
    'privacy.highlights.transparency.desc': 'Clear policies on data collection and usage',
    'privacy.highlights.control.title': 'User Control',
    'privacy.highlights.control.desc': 'You control your data and privacy settings',
    'privacy.sections.collection.title': 'Information We Collect',
    'privacy.sections.collection.personal.title': 'Personal Information',
    'privacy.sections.collection.personal.text': 'We collect personal information such as name, email, phone number, and professional credentials when you register for our services.',
    'privacy.sections.collection.medical.title': 'Medical Information',
    'privacy.sections.collection.medical.text': 'We process medical information including patient records, test results, and treatment history as part of our healthcare management services.',
    'privacy.sections.collection.usage.title': 'Usage Information',
    'privacy.sections.collection.usage.text': 'We collect information about how you use our platform to improve our services and user experience.',
    'privacy.sections.use.title': 'How We Use Information',
    'privacy.sections.use.medical.title': 'Medical Care Delivery',
    'privacy.sections.use.medical.text': 'Medical information is used solely for providing healthcare services and maintaining medical records.',
    'privacy.sections.use.operational.title': 'Operational Purposes',
    'privacy.sections.use.operational.text': 'We use your information to operate our services, process payments, and provide customer support.',
    'privacy.sections.use.improvement.title': 'Service Improvement',
    'privacy.sections.use.improvement.text': 'Anonymous usage data helps us improve our platform and develop new features.',
    'privacy.sections.sharing.title': 'Information Sharing',
    'privacy.sections.sharing.healthcare.title': 'Healthcare Providers',
    'privacy.sections.sharing.healthcare.text': 'Medical information is shared only with authorized healthcare providers involved in patient care.',
    'privacy.sections.sharing.legal.title': 'Legal Requirements',
    'privacy.sections.sharing.legal.text': 'We may disclose information when required by law or to protect health and safety.',
    'privacy.sections.sharing.consent.title': 'With Your Consent',
    'privacy.sections.sharing.consent.text': 'We share information with third parties only with your explicit consent.',
    'privacy.sections.security.title': 'Data Security',
    'privacy.sections.security.encryption.title': 'Encryption & Protection',
    'privacy.sections.security.encryption.text': 'All data is encrypted using industry-standard encryption both at rest and in transit.',
    'privacy.sections.security.access.title': 'Access Controls',
    'privacy.sections.security.access.text': 'Strict access controls ensure only authorized personnel can access your information.',
    'privacy.sections.security.compliance.title': 'Compliance Measures',
    'privacy.sections.security.compliance.text': 'We maintain compliance with HIPAA, GDPR, and other relevant privacy regulations.',
    'privacy.sections.rights.title': 'Your Rights',
    'privacy.sections.rights.access.title': 'Right to Access',
    'privacy.sections.rights.access.text': 'You have the right to access and receive a copy of your personal information.',
    'privacy.sections.rights.correction.title': 'Right to Correction',
    'privacy.sections.rights.correction.text': 'You can request corrections to inaccurate or incomplete information.',
    'privacy.sections.rights.deletion.title': 'Right to Deletion',
    'privacy.sections.rights.deletion.text': 'You may request deletion of your personal information, subject to legal requirements.',
    'privacy.sections.rights.portability.title': 'Data Portability',
    'privacy.sections.rights.portability.text': 'You have the right to receive your data in a portable format.',
    'privacy.sections.international.title': 'International Transfers',
    'privacy.sections.international.transfers.title': 'Data Transfers',
    'privacy.sections.international.transfers.text': 'When we transfer data internationally, we ensure appropriate safeguards are in place.',
    'privacy.sections.international.safeguards.title': 'Security Safeguards',
    'privacy.sections.international.safeguards.text': 'We use standard contractual clauses and other approved transfer mechanisms.',
    'privacy.contact.title': 'Contact Us',
    'privacy.contact.subtitle': 'Have questions about our privacy practices?',
    'privacy.contact.dpo.title': 'Data Protection Officer',
    'privacy.contact.dpo.name': 'Sarah Johnson, DPO',
    'privacy.contact.legal.title': 'Legal Department',
    'privacy.contact.legal.address': '123 Healthcare Ave, Medical City, MC 12345',
    'privacy.contact.button': 'Contact Privacy Team',

    // Terms of Service
    'terms.title': 'Terms of Service',
    'terms.hero.title': 'Terms of Service',
    'terms.hero.subtitle': 'Please read these terms carefully before using our healthcare management platform.',
    'terms.effectiveDate': 'Effective date',
    'terms.version': 'Version',
    'terms.notice.title': 'Important Notice:',
    'terms.notice.text': 'These terms constitute a legally binding agreement. By using our services, you agree to be bound by these terms.',
    'terms.tableOfContents': 'Table of Contents',
    'terms.keyPoints.agreement.title': 'Legal Agreement',
    'terms.keyPoints.agreement.desc': 'Binding contract between you and MediCore',
    'terms.keyPoints.compliance.title': 'Healthcare Compliance',
    'terms.keyPoints.compliance.desc': 'Full compliance with medical regulations',
    'terms.keyPoints.responsibility.title': 'Data Responsibility',
    'terms.keyPoints.responsibility.desc': 'Shared responsibility for data protection',
    'terms.keyPoints.liability.title': 'Limitation of Liability',
    'terms.keyPoints.liability.desc': 'Clear liability terms and limitations',
    'terms.sections.acceptance.title': 'Acceptance of Terms',
    'terms.sections.acceptance.agreement.title': 'Agreement to Terms',
    'terms.sections.acceptance.agreement.text': 'By accessing or using our healthcare management platform, you agree to be bound by these Terms of Service.',
    'terms.sections.acceptance.modifications.title': 'Modifications',
    'terms.sections.acceptance.modifications.text': 'We reserve the right to modify these terms at any time. Changes will be effective upon posting.',
    'terms.sections.services.title': 'Description of Services',
    'terms.sections.services.description.title': 'Platform Services',
    'terms.sections.services.description.text': 'We provide a comprehensive healthcare management platform including EMR, scheduling, billing, and related services.',
    'terms.sections.services.availability.title': 'Service Availability',
    'terms.sections.services.availability.text': 'We strive to maintain 99.9% uptime but cannot guarantee uninterrupted service availability.',
    'terms.sections.services.updates.title': 'Service Updates',
    'terms.sections.services.updates.text': 'We may update or modify our services to improve functionality and security.',
    'terms.sections.obligations.title': 'User Obligations',
    'terms.sections.obligations.account.title': 'Account Responsibility',
    'terms.sections.obligations.account.text': 'You are responsible for maintaining the confidentiality of your account credentials.',
    'terms.sections.obligations.compliance.title': 'Regulatory Compliance',
    'terms.sections.obligations.compliance.text': 'You must comply with all applicable healthcare regulations and professional standards.',
    'terms.sections.obligations.prohibited.title': 'Prohibited Uses',
    'terms.sections.obligations.prohibited.text': 'You may not use our services for illegal activities or in violation of professional ethics.',
    'terms.sections.data.title': 'Data Responsibility',
    'terms.sections.data.ownership.title': 'Data Ownership',
    'terms.sections.data.ownership.text': 'You retain ownership of all patient and clinical data entered into our system.',
    'terms.sections.data.backup.title': 'Data Backup',
    'terms.sections.data.backup.text': 'While we provide backup services, you are responsible for maintaining your own data backups.',
    'terms.sections.data.security.title': 'Data Security',
    'terms.sections.data.security.text': 'We implement industry-standard security measures, but you must also follow security best practices.',
    'terms.sections.payment.title': 'Payment Terms',
    'terms.sections.payment.billing.title': 'Billing Cycle',
    'terms.sections.payment.billing.text': 'Subscription fees are billed in advance on a monthly or annual basis as selected.',
    'terms.sections.payment.refunds.title': 'Refund Policy',
    'terms.sections.payment.refunds.text': 'Refunds are provided on a pro-rated basis for annual subscriptions cancelled within 30 days.',
    'terms.sections.payment.suspension.title': 'Service Suspension',
    'terms.sections.payment.suspension.text': 'Services may be suspended for non-payment after appropriate notice.',
    'terms.sections.liability.title': 'Limitation of Liability',
    'terms.sections.liability.limitation.title': 'Liability Limits',
    'terms.sections.liability.limitation.text': 'Our liability is limited to the amount paid by you for our services in the preceding 12 months.',
    'terms.sections.liability.medical.title': 'Medical Decisions',
    'terms.sections.liability.medical.text': 'Our platform is a tool only. You remain solely responsible for all medical decisions and patient care.',
    'terms.sections.liability.indemnification.title': 'Indemnification',
    'terms.sections.liability.indemnification.text': 'You agree to indemnify us against claims arising from your use of our services.',
    'terms.governing.title': 'Governing Law',
    'terms.governing.subtitle': 'Legal jurisdiction and dispute resolution',
    'terms.governing.jurisdiction.title': 'Jurisdiction',
    'terms.governing.jurisdiction.text': 'These terms are governed by the laws of the jurisdiction where our company is incorporated.',
    'terms.governing.disputes.title': 'Dispute Resolution',
    'terms.governing.disputes.text': 'Disputes will be resolved through binding arbitration in accordance with applicable arbitration rules.',
    'terms.governing.changes.title': 'Changes to Terms',
    'terms.governing.changes.text': 'We will notify you of material changes to these terms via email or platform notification.',
    'terms.contact.title': 'Contact Information',
    'terms.contact.subtitle': 'Get in touch with our legal team',
    'terms.contact.legal.title': 'Legal Department',
    'terms.contact.support.title': 'Customer Support',
    'terms.contact.support.hours': 'Available 24/7 for Enterprise customers',
    'terms.contact.button': 'Contact Legal Team',

    // Dashboard common translations
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Welcome to your dashboard',
    'dashboard.comingSoon': 'Coming soon...',
    'dashboard.addPatient': 'Add Patient',
    'dashboard.settingsComingSoon': 'Settings panel coming soon...',
    'dashboard.prescriptionsComingSoon': 'Prescriptions management coming soon...',
    'dashboard.insuranceClaimsComingSoon': 'Insurance claims module coming soon...',
    'dashboard.financialReportsComingSoon': 'Financial reports module coming soon...',
    'dashboard.testResultsComingSoon': 'Test results management coming soon...',
    'dashboard.dispensingComingSoon': 'Dispensing module coming soon...',
    'dashboard.appointmentSchedulerComingSoon': 'Appointment scheduler interface coming soon...',
    'dashboard.dataFlowComingSoon': 'Real-time data flow visualization coming soon...',
    'dashboard.requestNewAppointment': 'Request New Appointment',
    'dashboard.imagingStudiesComingSoon': 'Imaging studies management coming soon...',
    'dashboard.reportingComingSoon': 'Reporting module coming soon...',
    'dashboard.qualityControlComingSoon': 'Quality control module coming soon...',
    
    // Dashboard Stats
    'dashboard.stats.patients': 'Patients',
    'dashboard.stats.total': 'Total',
    'dashboard.stats.new': 'New',
    'dashboard.stats.active': 'Active',
    'dashboard.stats.appointments': 'Appointments',
    'dashboard.stats.today': 'Today',
    'dashboard.stats.upcoming': 'Upcoming',
    'dashboard.stats.completed': 'Completed',
    'dashboard.stats.cancelled': 'Cancelled',
    'dashboard.stats.revenue': 'Revenue',
    'dashboard.stats.month': 'This Month',
    'dashboard.stats.year': 'This Year',
    'dashboard.stats.pharmacy': 'Pharmacy',
    'dashboard.stats.totalItems': 'Total Items',
    'dashboard.stats.lowStock': 'Low Stock',
    'dashboard.stats.expired': 'Expired',
    'dashboard.stats.prescriptions': 'Prescriptions',
    'dashboard.stats.lab': 'Laboratory',
    'dashboard.stats.pending': 'Pending',
    'dashboard.stats.critical': 'Critical',
    'dashboard.stats.staff': 'Staff',
    'dashboard.stats.online': 'Online',
    'dashboard.stats.departments': 'Departments',
    
    // Dashboard Actions
    'dashboard.actions.quickActions': 'Quick Actions',
    'dashboard.actions.viewAll': 'View All',
    'dashboard.actions.refresh': 'Refresh',
    'dashboard.actions.export': 'Export',
    'dashboard.actions.filter': 'Filter',
    
    // Dashboard Sections
    'dashboard.sections.recentActivity': 'Recent Activity',
    'dashboard.sections.todayAppointments': "Today's Appointments",
    'dashboard.sections.pendingTasks': 'Pending Tasks',
    'dashboard.sections.alerts': 'Alerts',
    'dashboard.sections.statistics': 'Statistics',
    'dashboard.sections.performance': 'Performance',
    
    // Activity Types
    'dashboard.activity.appointment': 'Appointment',
    'dashboard.activity.patient': 'Patient',
    'dashboard.activity.lab': 'Lab',
    'dashboard.activity.prescription': 'Prescription',
    'dashboard.activity.revenue': 'Revenue',
    'dashboard.activity.newAppointment': 'New appointment booked',
    'dashboard.activity.labResult': 'Lab result critical',
    'dashboard.activity.newPatient': 'New patient registered',
    'dashboard.activity.prescriptionDispensed': 'Prescription dispensed',
    'dashboard.activity.paymentReceived': 'Payment received',
    
    // Time Periods
    'dashboard.period.today': 'Today',
    'dashboard.period.week': 'This Week',
    'dashboard.period.month': 'This Month',
    'dashboard.period.year': 'This Year',
    
    // Loading States
    'dashboard.loading.stats': 'Loading statistics...',
    'dashboard.loading.activity': 'Loading activity...',
    'dashboard.loading.data': 'Loading data...',
    
    // Additional Dashboard Translations
    'dashboard.totalPatients': 'Total Patients',
    'dashboard.todayAppointments': "Today's Appointments",
    'dashboard.todayRevenue': "Today's Revenue",
    'dashboard.systemStatus': 'System Status',
    'dashboard.staffOnline': 'Staff Online',
    'dashboard.upcoming': 'Upcoming',
    'dashboard.departments': 'Departments',
    'dashboard.staff': 'Staff',
    'dashboard.criticalAlerts': 'Critical Alerts',
    'dashboard.medicationsNeedReorder': 'Medications need reorder',
    'dashboard.expiredMedications': 'Expired medications',
    'dashboard.criticalLabResults': 'Critical lab results',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.systemPerformance': 'System Performance',
    'dashboard.serverLoad': 'Server Load',
    'dashboard.databaseUsage': 'Database Usage',
    'dashboard.storageUsage': 'Storage Usage',
    
    // Common translations
    'common.refresh': 'Refresh',
    'common.export': 'Export',
    'common.today': 'Today',
    'common.completed': 'Completed',
    'common.cancelled': 'Cancelled',
    'common.fromLastMonth': 'from last month',
    'common.fromYesterday': 'from yesterday',
    'common.fromLastWeek': 'from last week',
    'common.view': 'View',
    
    // Status
    'status.online': 'Online',
    
    // Appointments
    'appointments.title': 'Appointments',
    'appointments.schedule': 'Schedule Appointment',
    
    // Patients
    'patients.addPatient': 'Add Patient',
    
    // Pharmacy
    'pharmacy.lowStock': 'Low Stock',
    'pharmacy.expired': 'Expired',
    'pharmacy.addMedication': 'Add Medication',
    
    // Lab
    'lab.critical': 'Critical',
    
    // Reports
    'reports.generate': 'Generate Report',
    
    // Navigation
    'nav.quickActions': 'Quick Actions',
    
    // Patient Form
    'patient.form.title': 'Add New Patient',
    'patient.form.step': 'Step',
    'patient.form.of': 'of',
    'patient.form.personalInfo': 'Personal Information',
    'patient.form.contactInfo': 'Contact Information',
    'patient.form.emergencyContact': 'Emergency Contact',
    'patient.form.medicalInfo': 'Medical Information',
    'patient.form.insuranceInfo': 'Insurance & Additional Information',
    'patient.form.basicInfo': 'Basic Personal Information',
    'patient.form.uploadPhoto': 'Upload Photo',
    'patient.form.optional': 'Optional - Max 2MB',
    'patient.form.firstName': 'First Name (English)',
    'patient.form.lastName': 'Last Name (English)',
    'patient.form.arabicFirstName': 'First Name (Arabic)',
    'patient.form.arabicLastName': 'Last Name (Arabic)',
    'patient.form.dateOfBirth': 'Date of Birth',
    'patient.form.selectDate': 'Select date of birth',
    'patient.form.gender': 'Gender',
    'patient.form.selectGender': 'Select gender',
    'patient.form.male': 'Male',
    'patient.form.female': 'Female',
    'patient.form.other': 'Other',
    'patient.form.nationalId': 'National ID Number',
    'patient.form.mrn': 'Medical Record Number',
    'patient.form.autoGenerated': 'Auto-generated',
    'patient.form.nationality': 'Nationality',
    'patient.form.maritalStatus': 'Marital Status',
    'patient.form.selectMaritalStatus': 'Select marital status',
    'patient.form.single': 'Single',
    'patient.form.married': 'Married',
    'patient.form.divorced': 'Divorced',
    'patient.form.widowed': 'Widowed',
    'patient.form.phone': 'Primary Phone Number',
    'patient.form.alternativePhone': 'Alternative Phone',
    'patient.form.email': 'Email Address',
    'patient.form.address': 'Address',
    'patient.form.fullAddress': 'Full address',
    'patient.form.city': 'City',
    'patient.form.postalCode': 'Postal Code',
    'patient.form.emergencyContactTitle': 'Emergency Contact Person',
    'patient.form.emergencyContactDesc': 'Person to contact in case of emergency',
    'patient.form.fullName': 'Full Name',
    'patient.form.relationship': 'Relationship',
    'patient.form.selectRelationship': 'Select relationship',
    'patient.form.spouse': 'Spouse',
    'patient.form.father': 'Father',
    'patient.form.mother': 'Mother',
    'patient.form.brother': 'Brother',
    'patient.form.sister': 'Sister',
    'patient.form.son': 'Son',
    'patient.form.daughter': 'Daughter',
    'patient.form.friend': 'Friend',
    'patient.form.bloodType': 'Blood Type',
    'patient.form.selectBloodType': 'Select blood type',
    'patient.form.height': 'Height (cm)',
    'patient.form.weight': 'Weight (kg)',
    'patient.form.allergies': 'Allergies',
    'patient.form.addAllergy': 'Add new allergy',
    'patient.form.currentMedications': 'Current Medications',
    'patient.form.addMedication': 'Add new medication',
    'patient.form.medicalHistory': 'Medical History',
    'patient.form.addCondition': 'Add previous medical condition',
    'patient.form.smoking': 'Smoking',
    'patient.form.selectSmoking': 'Select smoking status',
    'patient.form.nonSmoker': 'Non-smoker',
    'patient.form.currentSmoker': 'Current smoker',
    'patient.form.formerSmoker': 'Former smoker',
    'patient.form.alcohol': 'Alcohol Consumption',
    'patient.form.selectAlcohol': 'Select alcohol consumption level',
    'patient.form.noAlcohol': 'Does not consume',
    'patient.form.occasionally': 'Occasionally',
    'patient.form.regularly': 'Regularly',
    'patient.form.insuranceTitle': 'Insurance Information',
    'patient.form.hasInsurance': 'Has medical insurance',
    'patient.form.insuranceProvider': 'Insurance Company',
    'patient.form.selectInsurance': 'Select insurance company',
    'patient.form.policyNumber': 'Policy Number',
    'patient.form.membershipNumber': 'Membership Number',
    'patient.form.insuranceClass': 'Insurance Class',
    'patient.form.selectClass': 'Select insurance class',
    'patient.form.classA': 'Class A',
    'patient.form.classB': 'Class B',
    'patient.form.classC': 'Class C',
    'patient.form.classVIP': 'VIP',
    'patient.form.additionalInfo': 'Additional Information',
    'patient.form.occupation': 'Occupation',
    'patient.form.employer': 'Employer',
    'patient.form.preferredLanguage': 'Preferred Language',
    'patient.form.notes': 'Additional Notes',
    'patient.form.notesPlaceholder': 'Any additional notes or information...',
    'patient.form.previous': 'Previous',
    'patient.form.next': 'Next',
    'patient.form.cancel': 'Cancel',
    'patient.form.save': 'Save Patient',
    'patient.form.saving': 'Saving...',
    'patient.form.required': 'Required',
    'patient.form.error.firstName': 'First name is required',
    'patient.form.error.lastName': 'Last name is required',
    'patient.form.error.dateOfBirth': 'Date of birth is required',
    'patient.form.error.gender': 'Gender is required',
    'patient.form.error.nationalId': 'National ID is required',
    'patient.form.error.phone': 'Phone number is required',
    'patient.form.error.address': 'Address is required',
    'patient.form.error.city': 'City is required',
    'patient.form.error.emergencyName': 'Emergency contact name is required',
    'patient.form.error.emergencyPhone': 'Emergency contact phone is required',
    'patient.form.error.emergencyRelationship': 'Relationship is required',

    // Patient Management
    'patients.title': 'Patient Management',
    'patients.totalPatients': '{count} Total Patients',
    'patients.addPatient': 'Add Patient',
    'patients.searchPlaceholder': 'Search by name, MRN, phone, or email...',
    'patients.noResults': 'No patients found',
    'patients.noPatients': 'No patients yet',
    'patients.tryDifferentSearch': 'Try a different search term',
    'patients.addFirstPatient': 'Add your first patient to get started',
    'patients.mrn': 'MRN',
    'patients.age': 'Age',
    'patients.lastVisit': 'Last Visit',
    'patients.allergies': 'Allergies',
    'patients.conditions': 'Conditions',
    'patients.personalInfo': 'Personal Information',
    'patients.medicalHistory': 'Medical History',
    'patients.insurance': 'Insurance',
    'patients.notes': 'Notes',
    'patients.dateOfBirth': 'Date of Birth',
    'patients.gender': 'Gender',
    'patients.male': 'Male',
    'patients.female': 'Female',
    'patients.other': 'Other',
    'patients.bloodType': 'Blood Type',
    'patients.emergencyContact': 'Emergency Contact',
    'patients.relationship': 'Relationship',
    'patients.noAllergies': 'No known allergies',
    'patients.medications': 'Current Medications',
    'patients.noMedications': 'No current medications',
    'patients.noMedicalHistory': 'No medical history recorded',
    'patients.insuranceProvider': 'Insurance Provider',
    'patients.policyNumber': 'Policy Number',
    'patients.groupNumber': 'Group Number',
    'patients.noInsurance': 'No insurance information',
    'patients.noNotes': 'No notes available',
    'patients.deletePatient': 'Delete Patient',
    'patients.deleteConfirmation': 'Are you sure you want to delete {patientName}? This action cannot be undone.',
    'common.notSpecified': 'Not specified',
    'common.notProvided': 'Not provided',
    'common.name': 'Name',
    'common.phone': 'Phone',
    'common.email': 'Email',
    'common.address': 'Address',
    'common.years': 'years',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.active': 'Active',
    'common.inactive': 'Inactive',

    // Radiology
    'radiology.title': 'Radiology & Medical Imaging',
    'radiology.newStudy': 'New Study',
    'radiology.dashboard': 'Dashboard',
    'radiology.studies': 'Studies',
    'radiology.worklist': 'Worklist',
    'radiology.reports': 'Reports',
    'radiology.viewer': 'DICOM Viewer',
    'radiology.totalStudies': 'Total Studies',
    'radiology.pendingReports': 'Pending Reports',
    'radiology.completedToday': 'Completed Today',
    'radiology.criticalFindings': 'Critical Findings',
    'radiology.modalityBreakdown': 'Modality Breakdown',
    'radiology.modalityDistribution': 'Study Distribution by Modality Type',
    'radiology.recentStudies': 'Recent Studies',
    'radiology.latestAddedStudies': 'Latest Added Studies',
    'radiology.fromYesterday': 'from yesterday',
    'radiology.patientName': 'Patient Name',
    'radiology.studyDate': 'Study Date',
    'radiology.modality': 'Modality',
    'radiology.bodyPart': 'Body Part',
    'radiology.studyDescription': 'Study Description',
    'radiology.status': 'Status',
    'radiology.actions': 'Actions',
    'radiology.scheduled': 'Scheduled',
    'radiology.inProgress': 'In Progress',
    'radiology.completed': 'Completed',
    'radiology.reported': 'Reported',
    'radiology.cancelled': 'Cancelled',
    'radiology.routine': 'Routine',
    'radiology.urgent': 'Urgent',
    'radiology.stat': 'STAT',
    'radiology.contrast': 'Contrast',
    'radiology.brightness': 'Brightness',
    'radiology.zoom': 'Zoom',
    'radiology.rotate': 'Rotate',
    'radiology.pan': 'Pan',
    'radiology.measurements': 'Measurements',
    'radiology.annotations': 'Annotations',
    'radiology.windowLevel': 'Window/Level',
    'radiology.distance': 'Distance',
    'radiology.angle': 'Angle',
    'radiology.area': 'Area',
    'radiology.rectangle': 'Rectangle',
    'radiology.circle': 'Circle',
    'radiology.arrow': 'Arrow',
    'radiology.text': 'Text',
    'radiology.imageControl': 'Image Control',
    'radiology.studyInfo': 'Study Information',
    'radiology.patient': 'Patient',
    'radiology.date': 'Date',
    'radiology.type': 'Type',
    'radiology.part': 'Part',
    'radiology.advancedViewer': 'Advanced DICOM Viewer',
    'radiology.selectStudyToView': 'Select a study from the studies list or worklist to view it in the advanced viewer',
    'radiology.goToStudies': 'Go to Studies',
    'radiology.goToWorklist': 'Go to Worklist',
    'radiology.noStudySelected': 'No study selected',
    'radiology.selectStudyFromList': 'Select a study from the studies list to view it',

    // Appointments Management
    'appointments.management': 'Appointments Management',
    'appointments.totalAppointments': '{count} Total Appointments',
    'appointments.dayView': 'Day View',
    'appointments.weekView': 'Week View',
    'appointments.monthView': 'Month View',
    'appointments.scheduleDescription': 'Schedule a new appointment for a patient',
    'appointments.patient': 'Patient',
    'appointments.selectPatient': 'Select patient',
    'appointments.doctor': 'Doctor',
    'appointments.selectDoctor': 'Select doctor',
    'appointments.datetime': 'Date & Time',
    'appointments.duration': 'Duration',
    'appointments.type': 'Type',
    'appointments.searchPlaceholder': 'Search appointments...',
    'appointments.noAppointments': 'No appointments scheduled',
    'appointments.noAppointmentsDescription': 'No appointments found for the selected date',
    'appointments.with': 'with',
    'appointments.scheduled': 'Scheduled',
    'appointments.confirmed': 'Confirmed',
    'appointments.inProgress': 'In Progress',
    'appointments.completed': 'Completed',
    'appointments.cancelled': 'Cancelled',
    'appointments.consultation': 'Consultation',
    'appointments.followUp': 'Follow-up',
    'appointments.procedure': 'Procedure',
    'appointments.emergency': 'Emergency',
    'appointments.low': 'Low',
    'appointments.medium': 'Medium',
    'appointments.high': 'High',
    'appointments.urgent': 'Urgent',
    'appointments.appointmentDetails': 'Appointment Details',
    'common.minutes': 'minutes',
    'common.calendar': 'Calendar',
    'common.allDoctors': 'All Doctors',
    'common.allStatuses': 'All Statuses',
    'common.status': 'Status',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.loading': 'Loading...',
    'common.comingSoon': 'Coming soon...',

    // Staff Management
    'staff.management': 'Staff Management',
    'staff.comprehensive': 'Comprehensive system for managing staff, attendance, and performance',
    'staff.totalStaff': 'Total Staff',
    'staff.active': 'Active',
    'staff.onLeave': 'On Leave',
    'staff.searchPlaceholder': 'Search...',
    'staff.dashboard': 'Dashboard',
    'staff.employees': 'Employees',
    'staff.attendance': 'Attendance',
    'staff.leaves': 'Leaves',
    'staff.totalEmployees': 'Total Employees',
    'staff.fromLastMonth': 'from last month',
    'staff.todayAttendance': 'Today\'s Attendance',
    'staff.attendanceRate': 'attendance rate',
    'staff.onLeaveToday': 'On Leave',
    'staff.pendingRequest': 'pending request',
    'staff.averagePerformance': 'Average Performance',
    'staff.fromLastReview': 'from last review',
    'staff.attendanceStatus': 'Today\'s Attendance Status',
    'staff.present': 'Present',
    'staff.late': 'Late',
    'staff.absent': 'Absent',
    'staff.departmentDistribution': 'Department Distribution',
    'staff.cardiology': 'Cardiology',
    'staff.nursing': 'Nursing',
    'staff.reception': 'Reception',
    'staff.laboratory': 'Laboratory',
    'staff.radiology': 'Radiology',
    'staff.quickStats': 'Quick Stats',
    'staff.activeEmployees': 'Active Employees',
    'staff.inactive': 'Inactive',
    'staff.newEmployees': 'New Employees',
    'staff.name': 'Name',
    'staff.position': 'Position',
    'staff.department': 'Department',
    'staff.hireDate': 'Hire Date',
    'staff.pendingLeaveRequests': 'Pending Leave Requests',
    'staff.annualLeave': 'Annual Leave',
    'staff.noLeaveRequests': 'No pending leave requests',
    'staff.days': 'days',
    'staff.approve': 'Approve',
    'staff.reject': 'Reject',
    'staff.sickLeave': 'Sick Leave',
    'staff.emergencyLeave': 'Emergency Leave',
    'staff.maternityLeave': 'Maternity Leave',
    'staff.employeeList': 'Employee List',
    'staff.employeeListContent': 'Employee list content will be added here',
    'staff.attendanceRecord': 'Attendance Record',
    'staff.attendanceRecordContent': 'Attendance record content will be added here',
    'staff.leaveManagement': 'Leave Management',
    'staff.leaveManagementContent': 'Leave management content will be added here',

    // Billing & Financial
    'billing.management': 'Billing & Financial Management',
    'billing.createInvoice': 'Create Invoice',
    'billing.recordPayment': 'Record Payment',
    'billing.dashboard': 'Dashboard',
    'billing.invoices': 'Invoices',
    'billing.payments': 'Payments',
    'billing.insurance': 'Insurance',
    'billing.reports': 'Financial Reports',
    'billing.totalRevenue': 'Total Revenue',
    'billing.pendingPayments': 'Pending Payments',
    'billing.completedPayments': 'Completed Payments',
    'billing.insuranceClaims': 'Insurance Claims',
    'billing.recentTransactions': 'Recent Transactions',
    'billing.latestTransactions': 'Latest financial transactions',
    'billing.paid': 'Paid',
    'billing.pending': 'Pending',
    'billing.overdue': 'Overdue',
    'billing.approved': 'Approved',
    'billing.rejected': 'Rejected',
    'billing.submitted': 'Submitted',
    'billing.underReview': 'Under Review',
    'billing.invoiceCreated': 'Invoice created successfully',
    'billing.paymentRecorded': 'Payment recorded successfully',
    'billing.invoiceNumber': 'Invoice Number',
    'billing.patientName': 'Patient Name',
    'billing.invoiceDate': 'Invoice Date',
    'billing.dueDate': 'Due Date',
    'billing.amount': 'Amount',
    'billing.paymentMethod': 'Payment Method',
    'billing.paymentDate': 'Payment Date',
    'billing.paymentId': 'Payment ID',
    'billing.claimNumber': 'Claim Number',
    'billing.insuranceProvider': 'Insurance Provider',
    'billing.claimStatus': 'Claim Status',
    'billing.claimAmount': 'Claim Amount',
    'billing.approvedAmount': 'Approved Amount',
    'billing.submissionDate': 'Submission Date',
    'billing.itemDescription': 'Description',
    'billing.quantity': 'Quantity',
    'billing.unitPrice': 'Unit Price',
    'billing.totalPrice': 'Total',
    'billing.subtotal': 'Subtotal',
    'billing.tax': 'Tax',
    'billing.discount': 'Discount',
    'billing.grandTotal': 'Grand Total',
    'billing.insuranceManagement': 'Insurance claims management',
    'billing.financialAnalytics': 'Financial reports and analytics',
    'billing.createInvoiceDescription': 'Create a new invoice for a patient',
    'billing.recordPaymentDescription': 'Record a new payment',
    'billing.patientId': 'Patient ID',
    'billing.invoiceItems': 'Invoice Items',
    'billing.addItem': 'Add Item',
    'billing.serviceDescription': 'Service description',
    'common.allStatuses': 'All Statuses',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.status': 'Status',
    'common.actions': 'Actions',

    // Pharmacy Management
    'pharmacy.title': 'Pharmacy Management',
    'pharmacy.overview': 'Manage medications, inventory, and prescriptions',
    'pharmacy.reports': 'Reports',
    'pharmacy.addMedication': 'Add Medication',
    'pharmacy.addMedicationDescription': 'Add new medication to inventory',
    'pharmacy.totalItems': 'Total Items',
    'pharmacy.lowStock': 'Low Stock',
    'pharmacy.nearExpiry': 'Near Expiry',
    'pharmacy.pendingPrescriptions': 'Pending Prescriptions',
    'pharmacy.inventory': 'Inventory',
    'pharmacy.prescriptions': 'Prescriptions',
    'pharmacy.searchMedications': 'Search medications...',
    'pharmacy.selectCategory': 'Select category',
    'pharmacy.inStock': 'In Stock',
    'pharmacy.outOfStock': 'Out of Stock',
    'pharmacy.expired': 'Expired',
    'pharmacy.noMedications': 'No medications found',
    'pharmacy.noMedicationsDescription': 'No medications match your search criteria',
    'pharmacy.genericName': 'Generic Name',
    'pharmacy.strength': 'Strength',
    'pharmacy.manufacturer': 'Manufacturer',
    'pharmacy.category': 'Category',
    'pharmacy.batchNumber': 'Batch Number',
    'pharmacy.expiryDate': 'Expiry Date',
    'pharmacy.supplier': 'Supplier',
    'pharmacy.location': 'Location',
    'pharmacy.stockLevel': 'Stock Level',
    'pharmacy.belowReorderLevel': 'Below reorder level',
    'pharmacy.unitPrice': 'Unit Price',
    'pharmacy.sellingPrice': 'Selling Price',
    'pharmacy.totalValue': 'Total Value',
    'pharmacy.searchPrescriptions': 'Search prescriptions...',
    'pharmacy.pending': 'Pending',
    'pharmacy.partiallyFilled': 'Partially Filled',
    'pharmacy.filled': 'Filled',
    'pharmacy.cancelled': 'Cancelled',
    'pharmacy.noPrescriptions': 'No prescriptions found',
    'pharmacy.noPrescriptionsDescription': 'No prescriptions match your search criteria',
    'pharmacy.prescriptionDate': 'Prescription Date',
    'pharmacy.medications': 'Medications',
    'common.allCategories': 'All Categories',

    // Laboratory Management
    'lab.title': 'Laboratory Management',
    'lab.overview': 'Manage lab tests, results, and quality control',
    'lab.reports': 'Reports',
    'lab.orderTest': 'Order Test',
    'lab.totalOrders': 'Total Orders',
    'lab.pending': 'Pending',
    'lab.inProgress': 'In Progress',
    'lab.completed': 'Completed',
    'lab.stat': 'STAT',
    'lab.urgent': 'Urgent',
    'lab.critical': 'Critical',
    'lab.orders': 'Orders',
    'lab.tests': 'Tests',
    'lab.results': 'Results',
    'lab.billing': 'Billing',
    'lab.notifications': 'Notifications',
    'lab.noOrders': 'No orders found',
    'lab.noOrdersDescription': 'No lab orders match your search criteria',
    'common.allPriorities': 'All Priorities'
  },

  ar: {
    // Landing Page Arabic
    'landing.brandName': 'ميديكور',
    'landing.tagline': 'إدارة صحية شاملة',
    'landing.nav.pricing': 'الأسعار',
    'landing.nav.features': 'المميزات',
    'landing.nav.about': 'حولنا',
    'landing.nav.contact': 'اتصل بنا',
    'landing.nav.login': 'تسجيل الدخول',
    'landing.nav.getStarted': 'ابدأ الآن',
    'landing.hero.badge': 'موثوق من قبل أكثر من 500 مؤسسة صحية',
    'landing.hero.title': 'حوّل إدارة مؤسستك الصحية',
    'landing.hero.subtitle': 'تبسيط العمليات، تحسين رعاية المرضى، وزيادة الكفاءة مع نظام إدارة المستشفيات الشامل.',
    'landing.hero.cta': 'ابدأ النسخة التجريبية',
    'landing.hero.watchDemo': 'شاهد العرض التوضيحي',
    'landing.stats.hospitals': 'مستشفى',
    'landing.stats.healthcare': 'محترف صحي',
    'landing.stats.patients': 'مريض',
    'landing.stats.uptime': 'وقت تشغيل النظام',
    'landing.features.title': 'حلول صحية شاملة',
    'landing.features.subtitle': 'كل ما تحتاجه لإدارة مؤسستك الصحية بكفاءة',
    'landing.features.patientCare.title': 'تميز في رعاية المرضى',
    'landing.features.patientCare.desc': 'إدارة شاملة للمرضى مع السجلات الصحية الإلكترونية وجدولة المواعيد وتنسيق الرعاية.',
    'landing.features.scheduling.title': 'جدولة ذكية',
    'landing.features.scheduling.desc': 'نظام حجز مواعيد ذكي مع تذكيرات تلقائية وتوفر فوري.',
    'landing.features.emr.title': 'السجلات الطبية الإلكترونية',
    'landing.features.emr.desc': 'سجلات صحية رقمية آمنة وشاملة مع وصول فوري ومشاركة سلسة.',
    'landing.features.analytics.title': 'تحليلات متقدمة',
    'landing.features.analytics.desc': 'تقارير وتحليلات قوية لتحسين العمليات ونتائج المرضى.',
    'landing.features.security.title': 'أمان على مستوى المؤسسات',
    'landing.features.security.desc': 'أمان متوافق مع HIPAA مع التشفير ومسارات التدقيق وضوابط الوصول.',
    'landing.features.collaboration.title': 'تعاون الفريق',
    'landing.features.collaboration.desc': 'أدوات تواصل وتعاون سلسة لفرق الرعاية الصحية.',
    'landing.testimonials.title': 'موثوق من قبل قادة الرعاية الصحية',
    'landing.testimonials.subtitle': 'اطلع على ما يقوله عملاؤنا',
    'landing.cta.title': 'مستعد لتحويل مؤسستك الصحية؟',
    'landing.cta.subtitle': 'انضم إلى آلاف المحترفين الصحيين الذين يثقون في ميديكور لعملياتهم اليومية.',
    'landing.cta.register': 'ابدأ النسخة التجريبية',
    'landing.cta.viewPricing': 'عرض الأسعار',
    'landing.footer.description': 'تمكين المؤسسات الصحية بحلول إدارية شاملة.',
    'landing.footer.product': 'المنتج',
    'landing.footer.company': 'الشركة',
    'landing.footer.legal': 'قانوني',
    'landing.footer.integrations': 'التكاملات',
    'landing.footer.api': 'واجهة برمجة التطبيقات',
    'landing.footer.about': 'حولنا',
    'landing.footer.careers': 'الوظائف',
    'landing.footer.contact': 'اتصل بنا',
    'landing.footer.blog': 'المدونة',
    'landing.footer.privacy': 'سياسة الخصوصية',
    'landing.footer.terms': 'شروط الخدمة',
    'landing.footer.security': 'الأمان',
    'landing.footer.compliance': 'الامتثال',
    'landing.footer.rights': 'جميع الحقوق محفوظة.',
    'landing.footer.global': 'تغطية عالمية',
    'landing.footer.secure': 'آمن ومتوافق',

    // Registration Page Arabic
    'register.title': 'إنشاء حسابك',
    'register.subtitle': 'انضم إلى آلاف المحترفين الصحيين',
    'register.step1Title': 'المعلومات الشخصية',
    'register.step1Desc': 'أدخل تفاصيلك الأساسية',
    'register.step2Title': 'اختر دورك',
    'register.step2Desc': 'اختر دورك المهني',
    'register.step3Title': 'التفاصيل المهنية',
    'register.step3Desc': 'أكمل ملفك المهني',
    'register.firstName': 'الاسم الأول',
    'register.lastName': 'اسم العائلة',
    'register.email': 'عنوان البريد الإلكتروني',
    'register.phone': 'رقم الهاتف',
    'register.password': 'كلمة المرور',
    'register.confirmPassword': 'تأكيد كلمة المرور',
    'register.passwordMismatch': 'كلمات المرور غير متطابقة',
    'register.selectRole': 'اختر دورك المهني',
    'register.roleHelp': 'اختر الدور الذي يصف منصبك بأفضل شكل',
    'register.categories.management': 'الإدارة',
    'register.categories.medical': 'طبي',
    'register.categories.technical': 'تقني',
    'register.categories.administration': 'إداري',
    'register.roleDescriptions.admin': 'إدارة النظام والإدارة العامة',
    'register.roleDescriptions.doctor': 'الاستشارات الطبية ورعاية المرضى',
    'register.roleDescriptions.nurse': 'رعاية المرضى والمساعدة الطبية',
    'register.roleDescriptions.receptionist': 'تسجيل المرضى وإدارة المواعيد',
    'register.roleDescriptions.lab_tech': 'فحوصات المختبر وتحليل العينات',
    'register.roleDescriptions.pharmacist': 'إدارة الأدوية والصرف',
    'register.roleDescriptions.radiologist': 'التصوير الطبي والخدمات التشخيصية',
    'register.specialization': 'التخصص',
    'register.selectSpecialization': 'اختر تخصصك',
    'register.licenseNumber': 'رقم الترخيص',
    'register.experience': 'سنوات الخبرة',
    'register.selectExperience': 'اختر مستوى الخبرة',
    'register.experience01': '0-1 سنة',
    'register.experience25': '2-5 سنوات',
    'register.experience610': '6-10 سنوات',
    'register.experience10plus': '10+ سنوات',
    'register.department': 'القسم',
    'register.notes': 'ملاحظات إضافية',
    'register.notesPlaceholder': 'أي معلومات إضافية أو متطلبات خاصة',
    'register.createAccount': 'إنشاء الحساب',
    'register.backToLogin': 'العودة لتسجيل الدخول',
    'register.error': 'فشل التسجيل. يرجى المحاولة مرة أخرى.',

    // Auth Extensions Arabic
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.createAccount': 'إنشاء حساب',
    'auth.backToHome': 'العودة للرئيسية',
    'auth.pricing': 'الأسعار',
    'auth.privacy': 'سياسة الخصوصية',
    'auth.terms': 'شروط الخدمة',

    // Add more Arabic translations as needed...
    // For brevity, I'll include key pricing translations
    'pricing.title': 'اختر خطتك',
    'pricing.hero.title': 'أسعار بسيطة وشفافة',
    'pricing.hero.subtitle': 'اختر الخطة المثالية لمؤسستك الصحية. جميع الخطط تشمل ميزاتنا الأساسية بدون رسوم خفية.',
    'pricing.billing.monthly': 'شهرياً',
    'pricing.billing.yearly': 'سنوياً',
    'pricing.getStarted': 'ابدأ الآن',

    // Privacy and Terms key translations
    'privacy.title': 'سياسة الخصوصية',
    'privacy.hero.title': 'خصوصيتك أولويتنا',
    'terms.title': 'شروط الخدمة',
    'terms.hero.title': 'شروط الخدمة',

    // Dashboard common translations
    'dashboard.title': 'لوحة التحكم',
    'dashboard.overview': 'مرحباً بك في لوحة التحكم',
    'dashboard.comingSoon': 'قريباً...',
    'dashboard.addPatient': 'إضافة مريض',
    'dashboard.settingsComingSoon': 'لوحة الإعدادات قريباً...',
    'dashboard.prescriptionsComingSoon': 'إدارة الوصفات الطبية قريباً...',
    'dashboard.insuranceClaimsComingSoon': 'وحدة مطالبات التأمين قريباً...',
    'dashboard.financialReportsComingSoon': 'وحدة التقارير المالية قريباً...',
    'dashboard.testResultsComingSoon': 'إدارة نتائج الفحوصات قريباً...',
    'dashboard.dispensingComingSoon': 'وحدة الصرف قريباً...',
    'dashboard.appointmentSchedulerComingSoon': 'واجهة جدولة المواعيد قريباً...',
    'dashboard.dataFlowComingSoon': 'تصور تدفق البيانات في الوقت الفعلي قريباً...',
    'dashboard.requestNewAppointment': 'طلب موعد جديد',
    'dashboard.imagingStudiesComingSoon': 'إدارة دراسات التصوير قريباً...',
    'dashboard.reportingComingSoon': 'وحدة التقارير قريباً...',
    'dashboard.qualityControlComingSoon': 'وحدة مراقبة الجودة قريباً...',
    
    // Dashboard Stats
    'dashboard.totalPatients': 'إجمالي المرضى',
    'dashboard.todayAppointments': 'مواعيد اليوم',
    'dashboard.todayRevenue': 'إيرادات اليوم',
    'dashboard.systemStatus': 'حالة النظام',
    'dashboard.staffOnline': 'الموظفون متصلون',
    'dashboard.upcoming': 'القادمة',
    'dashboard.departments': 'الأقسام',
    'dashboard.staff': 'الموظفون',
    'dashboard.criticalAlerts': 'التنبيهات الحرجة',
    'dashboard.medicationsNeedReorder': 'الأدوية تحتاج إعادة طلب',
    'dashboard.expiredMedications': 'أدوية منتهية الصلاحية',
    'dashboard.criticalLabResults': 'نتائج مختبر حرجة',
    'dashboard.recentActivity': 'النشاط الأخير',
    'dashboard.systemPerformance': 'أداء النظام',
    'dashboard.serverLoad': 'حمل الخادم',
    'dashboard.databaseUsage': 'استخدام قاعدة البيانات',
    'dashboard.storageUsage': 'استخدام التخزين',
    
    // Common translations
    'common.refresh': 'تحديث',
    'common.export': 'تصدير',
    'common.today': 'اليوم',
    'common.completed': 'مكتمل',
    'common.cancelled': 'ملغى',
    'common.fromLastMonth': 'من الشهر الماضي',
    'common.fromYesterday': 'من الأمس',
    'common.fromLastWeek': 'من الأسبوع الماضي',
    'common.view': 'عرض',
    
    // Status
    'status.online': 'متصل',
    
    // Appointments
    'appointments.title': 'المواعيد',
    'appointments.schedule': 'جدولة موعد',
    
    // Patients
    'patients.addPatient': 'إضافة مريض',
    
    // Pharmacy
    'pharmacy.lowStock': 'مخزون منخفض',
    'pharmacy.expired': 'منتهي الصلاحية',
    'pharmacy.addMedication': 'إضافة دواء',
    
    // Lab
    'lab.critical': 'حرج',
    
    // Reports
    'reports.generate': 'إنشاء تقرير',
    
    // Navigation
    'nav.quickActions': 'إجراءات سريعة',
    
    // Patient Form
    'patient.form.title': 'إضافة مريض جديد',
    'patient.form.step': 'الخطوة',
    'patient.form.of': 'من',
    'patient.form.personalInfo': 'المعلومات الشخصية',
    'patient.form.contactInfo': 'معلومات الاتصال',
    'patient.form.emergencyContact': 'جهة الاتصال للطوارئ',
    'patient.form.medicalInfo': 'المعلومات الطبية',
    'patient.form.insuranceInfo': 'التأمين والمعلومات الإضافية',
    'patient.form.basicInfo': 'المعلومات الشخصية الأساسية',
    'patient.form.uploadPhoto': 'رفع صورة',
    'patient.form.optional': 'اختياري - الحد الأقصى 2MB',
    'patient.form.firstName': 'الاسم الأول (بالإنجليزية)',
    'patient.form.lastName': 'اسم العائلة (بالإنجليزية)',
    'patient.form.arabicFirstName': 'الاسم الأول (بالعربية)',
    'patient.form.arabicLastName': 'اسم العائلة (بالعربية)',
    'patient.form.dateOfBirth': 'تاريخ الميلاد',
    'patient.form.selectDate': 'اختر تاريخ الميلاد',
    'patient.form.gender': 'الجنس',
    'patient.form.selectGender': 'اختر الجنس',
    'patient.form.male': 'ذكر',
    'patient.form.female': 'أنثى',
    'patient.form.other': 'آخر',
    'patient.form.nationalId': 'رقم الهوية الوطنية',
    'patient.form.mrn': 'رقم الملف الطبي',
    'patient.form.autoGenerated': 'سيتم إنشاؤه تلقائياً',
    'patient.form.nationality': 'الجنسية',
    'patient.form.maritalStatus': 'الحالة الاجتماعية',
    'patient.form.selectMaritalStatus': 'اختر الحالة الاجتماعية',
    'patient.form.single': 'أعزب',
    'patient.form.married': 'متزوج',
    'patient.form.divorced': 'مطلق',
    'patient.form.widowed': 'أرمل',
    'patient.form.phone': 'رقم الهاتف الأساسي',
    'patient.form.alternativePhone': 'رقم هاتف بديل',
    'patient.form.email': 'البريد الإلكتروني',
    'patient.form.address': 'العنوان',
    'patient.form.fullAddress': 'العنوان كاملاً',
    'patient.form.city': 'المدينة',
    'patient.form.postalCode': 'الرمز البريدي',
    'patient.form.emergencyContactTitle': 'جهة الاتصال في حالات الطوارئ',
    'patient.form.emergencyContactDesc': 'معلومات الشخص الذي يمكن الاتصال به في حالات الطوارئ',
    'patient.form.fullName': 'الاسم كاملاً',
    'patient.form.relationship': 'صلة القرابة',
    'patient.form.selectRelationship': 'اختر صلة القرابة',
    'patient.form.spouse': 'زوج/زوجة',
    'patient.form.father': 'والد',
    'patient.form.mother': 'والدة',
    'patient.form.brother': 'أخ',
    'patient.form.sister': 'أخت',
    'patient.form.son': 'ابن',
    'patient.form.daughter': 'ابنة',
    'patient.form.friend': 'صديق',
    'patient.form.bloodType': 'فصيلة الدم',
    'patient.form.selectBloodType': 'اختر فصيلة الدم',
    'patient.form.height': 'الطول (سم)',
    'patient.form.weight': 'الوزن (كغ)',
    'patient.form.allergies': 'الحساسيات',
    'patient.form.addAllergy': 'أضف حساسية جديدة',
    'patient.form.currentMedications': 'الأدوية الحالية',
    'patient.form.addMedication': 'أضف دواء جديد',
    'patient.form.medicalHistory': 'التاريخ المرضي',
    'patient.form.addCondition': 'أضف حالة طبية سابقة',
    'patient.form.smoking': 'التدخين',
    'patient.form.selectSmoking': 'اختر حالة التدخين',
    'patient.form.nonSmoker': 'غير مدخن',
    'patient.form.currentSmoker': 'مدخن حالياً',
    'patient.form.formerSmoker': 'مدخن سابق',
    'patient.form.alcohol': 'تناول الكحول',
    'patient.form.selectAlcohol': 'اختر مستوى تناول الكحول',
    'patient.form.noAlcohol': 'لا يتناول',
    'patient.form.occasionally': 'أحياناً',
    'patient.form.regularly': 'بانتظام',
    'patient.form.insuranceTitle': 'معلومات التأمين',
    'patient.form.hasInsurance': 'لديه تأمين طبي',
    'patient.form.insuranceProvider': 'شركة التأمين',
    'patient.form.selectInsurance': 'اختر شركة التأمين',
    'patient.form.policyNumber': 'رقم البوليصة',
    'patient.form.membershipNumber': 'رقم العضوية',
    'patient.form.insuranceClass': 'فئة التأمين',
    'patient.form.selectClass': 'اختر فئة التأمين',
    'patient.form.classA': 'الفئة A',
    'patient.form.classB': 'الفئة B',
    'patient.form.classC': 'الفئة C',
    'patient.form.classVIP': 'VIP',
    'patient.form.additionalInfo': 'معلومات إضافية',
    'patient.form.occupation': 'المهنة',
    'patient.form.employer': 'جهة العمل',
    'patient.form.preferredLanguage': 'اللغة المفضلة',
    'patient.form.notes': 'ملاحظات إضافية',
    'patient.form.notesPlaceholder': 'أي ملاحظات أو معلومات إضافية...',
    'patient.form.previous': 'السابق',
    'patient.form.next': 'التالي',
    'patient.form.cancel': 'إلغاء',
    'patient.form.save': 'حفظ المريض',
    'patient.form.saving': 'جاري الحفظ...',
    'patient.form.required': 'مطلوب',
    'patient.form.error.firstName': 'الاسم الأول مطلوب',
    'patient.form.error.lastName': 'اسم العائلة مطلوب',
    'patient.form.error.dateOfBirth': 'تاريخ الميلاد مطلوب',
    'patient.form.error.gender': 'الجنس مطلوب',
    'patient.form.error.nationalId': 'رقم الهوية مطلوب',
    'patient.form.error.phone': 'رقم الهاتف مطلوب',
    'patient.form.error.address': 'العنوان مطلوب',
    'patient.form.error.city': 'المدينة مطلوبة',
    'patient.form.error.emergencyName': 'اسم جهة الاتصال للطوارئ مطلوب',
    'patient.form.error.emergencyPhone': 'رقم هاتف الطوارئ مطلوب',
    'patient.form.error.emergencyRelationship': 'صلة القرابة مطلوبة',

    // Patient Management
    'patients.title': 'إدارة المرضى',
    'patients.totalPatients': '{count} إجمالي المرضى',
    'patients.addPatient': 'إضافة مريض',
    'patients.searchPlaceholder': 'البحث بالاسم، رقم الملف، الهاتف، أو البريد الإلكتروني...',
    'patients.noResults': 'لم يتم العثور على مرضى',
    'patients.noPatients': 'لا يوجد مرضى بعد',
    'patients.tryDifferentSearch': 'جرب مصطلح بحث مختلف',
    'patients.addFirstPatient': 'أضف أول مريض للبدء',
    'patients.mrn': 'رقم الملف الطبي',
    'patients.age': 'العمر',
    'patients.lastVisit': 'آخر زيارة',
    'patients.allergies': 'الحساسيات',
    'patients.conditions': 'الحالات',
    'patients.personalInfo': 'المعلومات الشخصية',
    'patients.medicalHistory': 'التاريخ المرضي',
    'patients.insurance': 'التأمين',
    'patients.notes': 'الملاحظات',
    'patients.dateOfBirth': 'تاريخ الميلاد',
    'patients.gender': 'الجنس',
    'patients.male': 'ذكر',
    'patients.female': 'أنثى',
    'patients.other': 'آخر',
    'patients.bloodType': 'فصيلة الدم',
    'patients.emergencyContact': 'جهة الاتصال للطوارئ',
    'patients.relationship': 'صلة القرابة',
    'patients.noAllergies': 'لا توجد حساسيات معروفة',
    'patients.medications': 'الأدوية الحالية',
    'patients.noMedications': 'لا توجد أدوية حالية',
    'patients.noMedicalHistory': 'لا يوجد تاريخ مرضي مسجل',
    'patients.insuranceProvider': 'شركة التأمين',
    'patients.policyNumber': 'رقم البوليصة',
    'patients.groupNumber': 'رقم المجموعة',
    'patients.noInsurance': 'لا توجد معلومات تأمين',
    'patients.noNotes': 'لا توجد ملاحظات متاحة',
    'patients.deletePatient': 'حذف المريض',
    'patients.deleteConfirmation': 'هل أنت متأكد من حذف {patientName}؟ لا يمكن التراجع عن هذا الإجراء.',
    'common.notSpecified': 'غير محدد',
    'common.notProvided': 'غير مقدم',
    'common.name': 'الاسم',
    'common.phone': 'الهاتف',
    'common.email': 'البريد الإلكتروني',
    'common.address': 'العنوان',
    'common.years': 'سنة',
    'common.filter': 'تصفية',
    'common.all': 'الكل',
    'common.active': 'نشط',
    'common.inactive': 'غير نشط',

    // Radiology
    'radiology.title': 'الأشعة والتصوير الطبي',
    'radiology.newStudy': 'دراسة جديدة',
    'radiology.dashboard': 'لوحة التحكم',
    'radiology.studies': 'الدراسات',
    'radiology.worklist': 'قائمة العمل',
    'radiology.reports': 'التقارير',
    'radiology.viewer': 'عارض DICOM',
    'radiology.totalStudies': 'إجمالي الدراسات',
    'radiology.pendingReports': 'التقارير المعلقة',
    'radiology.completedToday': 'المكتمل اليوم',
    'radiology.criticalFindings': 'النتائج الحرجة',
    'radiology.modalityBreakdown': 'توزيع أنواع الفحص',
    'radiology.modalityDistribution': 'توزيع الدراسات حسب نوع الفحص',
    'radiology.recentStudies': 'الدراسات الحديثة',
    'radiology.latestAddedStudies': 'آخر الدراسات المضافة',
    'radiology.fromYesterday': 'من الأمس',
    'radiology.patientName': 'اسم المريض',
    'radiology.studyDate': 'تاريخ الدراسة',
    'radiology.modality': 'نوع الفحص',
    'radiology.bodyPart': 'جزء الجسم',
    'radiology.studyDescription': 'وصف الدراسة',
    'radiology.status': 'الحالة',
    'radiology.actions': 'الإجراءات',
    'radiology.scheduled': 'مجدول',
    'radiology.inProgress': 'قيد التنفيذ',
    'radiology.completed': 'مكتمل',
    'radiology.reported': 'تم التقرير',
    'radiology.cancelled': 'ملغي',
    'radiology.routine': 'عادي',
    'radiology.urgent': 'عاجل',
    'radiology.stat': 'طارئ',
    'radiology.contrast': 'التباين',
    'radiology.brightness': 'السطوع',
    'radiology.zoom': 'التكبير',
    'radiology.rotate': 'الدوران',
    'radiology.pan': 'التحريك',
    'radiology.measurements': 'القياسات',
    'radiology.annotations': 'التعليقات',
    'radiology.windowLevel': 'النافذة/المستوى',
    'radiology.distance': 'المسافة',
    'radiology.angle': 'الزاوية',
    'radiology.area': 'المساحة',
    'radiology.rectangle': 'مستطيل',
    'radiology.circle': 'دائرة',
    'radiology.arrow': 'سهم',
    'radiology.text': 'نص',
    'radiology.imageControl': 'التحكم في الصورة',
    'radiology.studyInfo': 'معلومات الدراسة',
    'radiology.patient': 'المريض',
    'radiology.date': 'التاريخ',
    'radiology.type': 'النوع',
    'radiology.part': 'الجزء',
    'radiology.advancedViewer': 'عارض DICOM المتطور',
    'radiology.selectStudyToView': 'اختر دراسة من قائمة الدراسات أو قائمة العمل لعرضها في العارض المتقدم',
    'radiology.goToStudies': 'اذهب إلى الدراسات',
    'radiology.goToWorklist': 'اذهب إلى قائمة العمل',
    'radiology.noStudySelected': 'لا توجد دراسة محددة',
    'radiology.selectStudyFromList': 'اختر دراسة من قائمة الدراسات لعرضها',

    // Appointments Management
    'appointments.management': 'إدارة المواعيد',
    'appointments.totalAppointments': '{count} إجمالي المواعيد',
    'appointments.dayView': 'عرض اليوم',
    'appointments.weekView': 'عرض الأسبوع',
    'appointments.monthView': 'عرض الشهر',
    'appointments.scheduleDescription': 'جدولة موعد جديد للمريض',
    'appointments.patient': 'المريض',
    'appointments.selectPatient': 'اختر المريض',
    'appointments.doctor': 'الطبيب',
    'appointments.selectDoctor': 'اختر الطبيب',
    'appointments.datetime': 'التاريخ والوقت',
    'appointments.duration': 'المدة',
    'appointments.type': 'النوع',
    'appointments.searchPlaceholder': 'البحث في المواعيد...',
    'appointments.noAppointments': 'لا توجد مواعيد مجدولة',
    'appointments.noAppointmentsDescription': 'لم يتم العثور على مواعيد للتاريخ المحدد',
    'appointments.with': 'مع',
    'appointments.scheduled': 'مجدول',
    'appointments.confirmed': 'مؤكد',
    'appointments.inProgress': 'قيد التنفيذ',
    'appointments.completed': 'مكتمل',
    'appointments.cancelled': 'ملغي',
    'appointments.consultation': 'استشارة',
    'appointments.followUp': 'متابعة',
    'appointments.procedure': 'إجراء',
    'appointments.emergency': 'طوارئ',
    'appointments.low': 'منخفض',
    'appointments.medium': 'متوسط',
    'appointments.high': 'عالي',
    'appointments.urgent': 'عاجل',
    'appointments.appointmentDetails': 'تفاصيل الموعد',
    'common.minutes': 'دقيقة',
    'common.calendar': 'التقويم',
    'common.allDoctors': 'جميع الأطباء',
    'common.allStatuses': 'جميع الحالات',
    'common.status': 'الحالة',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.loading': 'جاري التحميل...',
    'common.comingSoon': 'قريباً...',

    // Staff Management
    'staff.management': 'إدارة الموظفين',
    'staff.comprehensive': 'نظام متكامل لإدارة الموظفين والحضور والأداء',
    'staff.totalStaff': 'إجمالي الموظفين',
    'staff.active': 'نشط',
    'staff.onLeave': 'في إجازة',
    'staff.searchPlaceholder': 'بحث...',
    'staff.dashboard': 'لوحة التحكم',
    'staff.employees': 'الموظفون',
    'staff.attendance': 'الحضور',
    'staff.leaves': 'الإجازات',
    'staff.totalEmployees': 'إجمالي الموظفين',
    'staff.fromLastMonth': 'من الشهر الماضي',
    'staff.todayAttendance': 'الحضور اليوم',
    'staff.attendanceRate': 'معدل الحضور',
    'staff.onLeaveToday': 'في إجازة',
    'staff.pendingRequest': 'طلب معلق',
    'staff.averagePerformance': 'متوسط الأداء',
    'staff.fromLastReview': 'من التقييم السابق',
    'staff.attendanceStatus': 'حالة الحضور اليوم',
    'staff.present': 'حاضر',
    'staff.late': 'متأخر',
    'staff.absent': 'غائب',
    'staff.departmentDistribution': 'توزيع الأقسام',
    'staff.cardiology': 'القلبية',
    'staff.nursing': 'التمريض',
    'staff.reception': 'الاستقبال',
    'staff.laboratory': 'المختبر',
    'staff.radiology': 'الأشعة',
    'staff.quickStats': 'إحصائيات سريعة',
    'staff.activeEmployees': 'الموظفون النشطون',
    'staff.inactive': 'غير نشطين',
    'staff.newEmployees': 'الموظفون الجدد',
    'staff.name': 'الاسم',
    'staff.position': 'المنصب',
    'staff.department': 'القسم',
    'staff.hireDate': 'تاريخ التوظيف',
    'staff.pendingLeaveRequests': 'طلبات الإجازة المعلقة',
    'staff.annualLeave': 'إجازة سنوية',
    'staff.noLeaveRequests': 'لا توجد طلبات إجازة معلقة',
    'staff.days': 'أيام',
    'staff.approve': 'موافقة',
    'staff.reject': 'رفض',
    'staff.sickLeave': 'إجازة مرضية',
    'staff.emergencyLeave': 'إجازة طارئة',
    'staff.maternityLeave': 'إجازة أمومة',
    'staff.employeeList': 'قائمة الموظفين',
    'staff.employeeListContent': 'ستتم إضافة محتوى قائمة الموظفين هنا',
    'staff.attendanceRecord': 'سجل الحضور',
    'staff.attendanceRecordContent': 'ستتم إضافة محتوى سجل الحضور هنا',
    'staff.leaveManagement': 'إدارة الإجازات',
    'staff.leaveManagementContent': 'ستتم إضافة محتوى إدارة الإجازات هنا',

    // Billing & Financial
    'billing.management': 'الفوترة والإدارة المالية',
    'billing.createInvoice': 'إنشاء فاتورة',
    'billing.recordPayment': 'تسجيل دفعة',
    'billing.dashboard': 'لوحة التحكم',
    'billing.invoices': 'الفواتير',
    'billing.payments': 'المدفوعات',
    'billing.insurance': 'التأمين',
    'billing.reports': 'التقارير المالية',
    'billing.totalRevenue': 'إجمالي الإيرادات',
    'billing.pendingPayments': 'المدفوعات المعلقة',
    'billing.completedPayments': 'المدفوعات المكتملة',
    'billing.insuranceClaims': 'مطالبات التأمين',
    'billing.recentTransactions': 'المعاملات الأخيرة',
    'billing.latestTransactions': 'آخر المعاملات المالية',
    'billing.paid': 'مدفوع',
    'billing.pending': 'معلق',
    'billing.overdue': 'متأخر',
    'billing.approved': 'معتمد',
    'billing.rejected': 'مرفوض',
    'billing.submitted': 'مقدم',
    'billing.underReview': 'قيد المراجعة',
    'billing.invoiceCreated': 'تم إنشاء الفاتورة بنجاح',
    'billing.paymentRecorded': 'تم تسجيل الدفعة بنجاح',
    'billing.invoiceNumber': 'رقم الفاتورة',
    'billing.patientName': 'اسم المريض',
    'billing.invoiceDate': 'تاريخ الفاتورة',
    'billing.dueDate': 'تاريخ الاستحقاق',
    'billing.amount': 'المبلغ',
    'billing.paymentMethod': 'طريقة الدفع',
    'billing.paymentDate': 'تاريخ الدفع',
    'billing.paymentId': 'رقم الدفعة',
    'billing.claimNumber': 'رقم المطالبة',
    'billing.insuranceProvider': 'مقدم التأمين',
    'billing.claimStatus': 'حالة المطالبة',
    'billing.claimAmount': 'مبلغ المطالبة',
    'billing.approvedAmount': 'المبلغ المعتمد',
    'billing.submissionDate': 'تاريخ التقديم',
    'billing.itemDescription': 'الوصف',
    'billing.quantity': 'الكمية',
    'billing.unitPrice': 'سعر الوحدة',
    'billing.totalPrice': 'الإجمالي',
    'billing.subtotal': 'المجموع الفرعي',
    'billing.tax': 'الضريبة',
    'billing.discount': 'الخصم',
    'billing.grandTotal': 'المجموع الإجمالي',
    'billing.insuranceManagement': 'إدارة مطالبات التأمين الطبي',
    'billing.financialAnalytics': 'التقارير والتحليلات المالية',
    'billing.createInvoiceDescription': 'إنشاء فاتورة جديدة للمريض',
    'billing.recordPaymentDescription': 'تسجيل دفعة جديدة',
    'billing.patientId': 'معرف المريض',
    'billing.invoiceItems': 'بنود الفاتورة',
    'billing.addItem': 'إضافة بند',
    'billing.serviceDescription': 'وصف الخدمة',
    'common.allStatuses': 'جميع الحالات',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.status': 'الحالة',
    'common.actions': 'الإجراءات',

    // Pharmacy Management
    'pharmacy.title': 'إدارة الصيدلية',
    'pharmacy.overview': 'إدارة الأدوية والمخزون والوصفات الطبية',
    'pharmacy.reports': 'التقارير',
    'pharmacy.addMedication': 'إضافة دواء',
    'pharmacy.addMedicationDescription': 'إضافة دواء جديد إلى المخزون',
    'pharmacy.totalItems': 'إجمالي الأصناف',
    'pharmacy.lowStock': 'مخزون منخفض',
    'pharmacy.nearExpiry': 'قريب من انتهاء الصلاحية',
    'pharmacy.pendingPrescriptions': 'الوصفات المعلقة',
    'pharmacy.inventory': 'المخزون',
    'pharmacy.prescriptions': 'الوصفات الطبية',
    'pharmacy.searchMedications': 'البحث عن الأدوية...',
    'pharmacy.selectCategory': 'اختر الفئة',
    'pharmacy.inStock': 'متوفر',
    'pharmacy.outOfStock': 'غير متوفر',
    'pharmacy.expired': 'منتهي الصلاحية',
    'pharmacy.noMedications': 'لم يتم العثور على أدوية',
    'pharmacy.noMedicationsDescription': 'لا توجد أدوية تطابق معايير البحث',
    'pharmacy.genericName': 'الاسم العام',
    'pharmacy.strength': 'التركيز',
    'pharmacy.manufacturer': 'الشركة المصنعة',
    'pharmacy.category': 'الفئة',
    'pharmacy.batchNumber': 'رقم الدفعة',
    'pharmacy.expiryDate': 'تاريخ انتهاء الصلاحية',
    'pharmacy.supplier': 'المورد',
    'pharmacy.location': 'الموقع',
    'pharmacy.stockLevel': 'مستوى المخزون',
    'pharmacy.belowReorderLevel': 'أقل من مستوى إعادة الطلب',
    'pharmacy.unitPrice': 'سعر الوحدة',
    'pharmacy.sellingPrice': 'سعر البيع',
    'pharmacy.totalValue': 'القيمة الإجمالية',
    'pharmacy.searchPrescriptions': 'البحث في الوصفات...',
    'pharmacy.pending': 'معلق',
    'pharmacy.partiallyFilled': 'مصروف جزئياً',
    'pharmacy.filled': 'مصروف',
    'pharmacy.cancelled': 'ملغي',
    'pharmacy.noPrescriptions': 'لم يتم العثور على وصفات',
    'pharmacy.noPrescriptionsDescription': 'لا توجد وصفات تطابق معايير البحث',
    'pharmacy.prescriptionDate': 'تاريخ الوصفة',
    'pharmacy.medications': 'الأدوية',
    'common.allCategories': 'جميع الفئات',

    // Laboratory Management
    'lab.title': 'إدارة المختبر',
    'lab.overview': 'إدارة الفحوصات والنتائج ومراقبة الجودة',
    'lab.reports': 'التقارير',
    'lab.orderTest': 'طلب فحص',
    'lab.totalOrders': 'إجمالي الطلبات',
    'lab.pending': 'معلق',
    'lab.inProgress': 'قيد التنفيذ',
    'lab.completed': 'مكتمل',
    'lab.stat': 'طارئ',
    'lab.urgent': 'عاجل',
    'lab.critical': 'حرج',
    'lab.orders': 'الطلبات',
    'lab.tests': 'الفحوصات',
    'lab.results': 'النتائج',
    'lab.billing': 'الفوترة',
    'lab.notifications': 'الإشعارات',
    'lab.noOrders': 'لم يتم العثور على طلبات',
    'lab.noOrdersDescription': 'لا توجد طلبات مختبر تطابق معايير البحث',
    'common.allPriorities': 'جميع الأولويات'
  }
};

export default extendedTranslations;