export const translations = {
  en: {
    title: 'Pharmacy Dashboard',
    prescriptions: 'Prescriptions',
    inventory: 'Inventory',
    dispensing: 'Dispensing',
    reports: 'Reports',
    pendingPrescriptions: 'Pending Prescriptions',
    lowStock: 'Low Stock Items',
    expiringItems: 'Expiring Soon',
    todayDispensed: "Today's Dispensed",
    searchPrescriptions: 'Search prescriptions...',
    searchMedications: 'Search medications...',
    patientName: 'Patient Name',
    doctor: 'Doctor',
    medication: 'Medication',
    dosage: 'Dosage',
    quantity: 'Quantity',
    instructions: 'Instructions',
    prescribedDate: 'Prescribed Date',
    status: 'Status',
    pending: 'Pending',
    dispensed: 'Dispensed',
    partiallyDispensed: 'Partially Dispensed',
    cancelled: 'Cancelled',
    dispense: 'Dispense',
    dispenseAll: 'Dispense All',
    viewDetails: 'View Details',
    medicationName: 'Medication Name',
    currentStock: 'Current Stock',
    minimumStock: 'Minimum Stock',
    expiryDate: 'Expiry Date',
    batchNumber: 'Batch Number',
    supplier: 'Supplier',
    costPrice: 'Cost Price',
    sellingPrice: 'Selling Price',
    addStock: 'Add Stock',
    updateStock: 'Update Stock',
    stockLevel: 'Stock Level',
    reorderLevel: 'Reorder Level',
    expiresIn: 'Expires in',
    days: 'days',
    lowStockAlert: 'Low Stock Alert',
    expiryAlert: 'Expiry Alert',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    medicationDispensed: 'Medication dispensed successfully',
    stockUpdated: 'Stock updated successfully',
    noItems: 'No items found',
    noPrescriptions: 'No prescriptions found',
    totalValue: 'Total Value',
    monthlyDispensed: 'Monthly Dispensed',
    averageDaily: 'Average Daily',
    topMedications: 'Top Medications',
  },
  ar: {
    title: 'لوحة تحكم الصيدلية',
    prescriptions: 'الوصفات الطبية',
    inventory: 'المخزون',
    dispensing: 'الصرف',
    reports: 'التقارير',
    pendingPrescriptions: 'الوصفات المعلقة',
    lowStock: 'أصناف قليلة المخزون',
    expiringItems: 'منتهية الصلاحية قريباً',
    todayDispensed: 'مصروف اليوم',
    searchPrescriptions: 'البحث عن الوصفات...',
    searchMedications: 'البحث عن الأدوية...',
    patientName: 'اسم المريض',
    doctor: 'الطبيب',
    medication: 'الدواء',
    dosage: 'الجرعة',
    quantity: 'الكمية',
    instructions: 'التعليمات',
    prescribedDate: 'تاريخ الوصف',
    status: 'الحالة',
    pending: 'معلق',
    dispensed: 'مصروف',
    partiallyDispensed: 'مصروف جزئياً',
    cancelled: 'ملغي',
    dispense: 'صرف',
    dispenseAll: 'صرف الكل',
    viewDetails: 'عرض التفاصيل',
    medicationName: 'اسم الدواء',
    currentStock: 'المخزون الحالي',
    minimumStock: 'الحد الأدنى للمخزون',
    expiryDate: 'تاريخ انتهاء الصلاحية',
    batchNumber: 'رقم الدفعة',
    supplier: 'المورد',
    costPrice: 'سعر التكلفة',
    sellingPrice: 'سعر البيع',
    addStock: 'إضافة مخزون',
    updateStock: 'تحديث المخزون',
    stockLevel: 'مستوى المخزون',
    reorderLevel: 'مستوى إعادة الطلب',
    expiresIn: 'تنتهي في',
    days: 'يوم',
    lowStockAlert: 'تنبيه نقص مخزون',
    expiryAlert: 'تنبيه انتهاء صلاحية',
    outOfStock: 'نفد المخزون',
    inStock: 'متوفر',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجح',
    medicationDispensed: 'تم صرف الدواء بنجاح',
    stockUpdated: 'تم تحديث المخزون بنجاح',
    noItems: 'لم يتم العثور على عناصر',
    noPrescriptions: 'لم يتم العثور على وصفات',
    totalValue: 'القيمة الإجمالية',
    monthlyDispensed: 'مصروف شهرياً',
    averageDaily: 'متوسط يومي',
    topMedications: 'أهم الأدوية',
  }
};

export const mockInventory = [
  {
    id: 'med1',
    name: 'Paracetamol 500mg',
    currentStock: 150,
    minimumStock: 50,
    expiryDate: '2025-06-15',
    batchNumber: 'PCT2024-A1',
    supplier: 'PharmaCorp',
    costPrice: 0.25,
    sellingPrice: 0.50,
    category: 'Analgesic'
  },
  {
    id: 'med2',
    name: 'Amoxicillin 250mg',
    currentStock: 25,
    minimumStock: 30,
    expiryDate: '2025-03-20',
    batchNumber: 'AMX2024-B2',
    supplier: 'MediSupply',
    costPrice: 0.80,
    sellingPrice: 1.50,
    category: 'Antibiotic'
  },
  {
    id: 'med3',
    name: 'Ibuprofen 400mg',
    currentStock: 0,
    minimumStock: 40,
    expiryDate: '2025-08-10',
    batchNumber: 'IBU2024-C3',
    supplier: 'PharmaCorp',
    costPrice: 0.35,
    sellingPrice: 0.70,
    category: 'NSAID'
  },
  {
    id: 'med4',
    name: 'Metformin 500mg',
    currentStock: 200,
    minimumStock: 60,
    expiryDate: '2025-12-31',
    batchNumber: 'MET2024-D4',
    supplier: 'DiabetesCare',
    costPrice: 0.15,
    sellingPrice: 0.30,
    category: 'Antidiabetic'
  },
  {
    id: 'med5',
    name: 'Omeprazole 20mg',
    currentStock: 80,
    minimumStock: 25,
    expiryDate: '2025-01-15',
    batchNumber: 'OME2024-E5',
    supplier: 'GastroMed',
    costPrice: 0.45,
    sellingPrice: 0.90,
    category: 'PPI'
  }
];

export const mockPrescriptions = [
  {
    id: 'rx1',
    patientName: 'Ahmed Hassan',
    doctorName: 'Dr. Sara Mohamed',
    medications: [
      { name: 'Paracetamol 500mg', dosage: '1 tablet', quantity: 20, instructions: 'Take twice daily after meals' },
      { name: 'Amoxicillin 250mg', dosage: '1 capsule', quantity: 15, instructions: 'Take three times daily before meals' }
    ],
    prescribedDate: '2024-12-01',
    status: 'pending',
    priority: 'normal'
  },
  {
    id: 'rx2',
    patientName: 'Fatima Ali',
    doctorName: 'Dr. Omar Khan',
    medications: [
      { name: 'Metformin 500mg', dosage: '1 tablet', quantity: 60, instructions: 'Take once daily with breakfast' }
    ],
    prescribedDate: '2024-12-01',
    status: 'dispensed',
    priority: 'normal'
  },
  {
    id: 'rx3',
    patientName: 'Mohamed Salah',
    doctorName: 'Dr. Ahmed Hassan',
    medications: [
      { name: 'Ibuprofen 400mg', dosage: '1 tablet', quantity: 10, instructions: 'Take as needed for pain' },
      { name: 'Omeprazole 20mg', dosage: '1 capsule', quantity: 30, instructions: 'Take once daily before breakfast' }
    ],
    prescribedDate: '2024-12-01',
    status: 'pending',
    priority: 'urgent'
  }
];