export const translations = {
  en: {
    title: 'Laboratory Dashboard',
    pendingTests: 'Pending Tests',
    completedTests: 'Completed Tests',
    testResults: 'Test Results',
    qualityControl: 'Quality Control',
    hl7Integration: 'HL7 Integration',
    testOrders: 'Test Orders',
    results: 'Results',
    searchTests: 'Search tests...',
    patientName: 'Patient Name',
    testType: 'Test Type',
    orderedBy: 'Ordered By',
    orderDate: 'Order Date',
    sampleId: 'Sample ID',
    testName: 'Test Name',
    normalValue: 'Normal Value',
    result: 'Result',
    unit: 'Unit',
    status: 'Status',
    pending: 'Pending',
    inProgress: 'In Progress',
    completed: 'Completed',
    urgent: 'Urgent',
    normal: 'Normal',
    abnormal: 'Abnormal',
    critical: 'Critical',
    enterResults: 'Enter Results',
    saveResults: 'Save Results',
    cancel: 'Cancel',
    viewReport: 'View Report',
    printResults: 'Print Results',
    notes: 'Notes',
    interpretation: 'Interpretation',
    referenceRange: 'Reference Range',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    resultsUpdated: 'Test results updated successfully',
    noTests: 'No tests found',
    todayTests: "Today's Tests",
    completedToday: 'Completed Today',
    pendingResults: 'Pending Results',
    criticalResults: 'Critical Results',
  },
  ar: {
    title: 'لوحة تحكم المختبر',
    pendingTests: 'الفحوصات المعلقة',
    completedTests: 'الفحوصات المكتملة',
    testResults: 'نتائج الفحوصات',
    qualityControl: 'مراقبة الجودة',
    hl7Integration: 'تكامل HL7',
    testOrders: 'طلبات الفحص',
    results: 'النتائج',
    searchTests: 'البحث عن الفحوصات...',
    patientName: 'اسم المريض',
    testType: 'نوع الفحص',
    orderedBy: 'طلب من',
    orderDate: 'تاريخ الطلب',
    sampleId: 'رقم العينة',
    testName: 'اسم الفحص',
    normalValue: 'القيمة الطبيعية',
    result: 'النتيجة',
    unit: 'الوحدة',
    status: 'الحالة',
    pending: 'معلق',
    inProgress: 'قيد التنفيذ',
    completed: 'مكتمل',
    urgent: 'عاجل',
    normal: 'طبيعي',
    abnormal: 'غير طبيعي',
    critical: 'حرج',
    enterResults: 'إدخال النتائج',
    saveResults: 'حفظ النتائج',
    cancel: 'إلغاء',
    viewReport: 'عرض التقرير',
    printResults: 'طباعة النتائج',
    notes: 'ملاحظات',
    interpretation: 'التفسير',
    referenceRange: 'المدى المرجعي',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجح',
    resultsUpdated: 'تم تحديث نتائج الفحص بنجاح',
    noTests: 'لم يتم العثور على فحوصات',
    todayTests: 'فحوصات اليوم',
    completedToday: 'مكتمل اليوم',
    pendingResults: 'نتائج معلقة',
    criticalResults: 'نتائج حرجة',
  }
};

// Mock lab tests data
export const labTestTypes = [
  { id: 'cbc', name: 'Complete Blood Count', normalRange: '4.5-11.0 x10³/μL' },
  { id: 'glucose', name: 'Blood Glucose', normalRange: '70-100 mg/dL' },
  { id: 'cholesterol', name: 'Total Cholesterol', normalRange: '<200 mg/dL' },
  { id: 'creatinine', name: 'Serum Creatinine', normalRange: '0.6-1.2 mg/dL' },
  { id: 'liver', name: 'Liver Function Tests', normalRange: 'Variable' },
  { id: 'thyroid', name: 'Thyroid Function', normalRange: 'Variable' },
  { id: 'urine', name: 'Urinalysis', normalRange: 'Variable' },
  { id: 'lipid', name: 'Lipid Profile', normalRange: 'Variable' },
];

export const mockLabOrders = [
  {
    id: 'lab_order:001',
    patientName: 'Ahmed Hassan',
    testType: 'Complete Blood Count',
    orderedBy: 'demo-doctor',
    createdAt: new Date().toISOString(),
    status: 'pending',
    results: null,
    priority: 'normal'
  },
  {
    id: 'lab_order:002',
    patientName: 'Fatima Ali',
    testType: 'Blood Glucose',
    orderedBy: 'demo-doctor',
    createdAt: new Date().toISOString(),
    status: 'completed',
    results: { value: '95', unit: 'mg/dL', status: 'normal' },
    priority: 'urgent'
  },
  {
    id: 'lab_order:003',
    patientName: 'Mohamed Salah',
    testType: 'Liver Function Tests',
    orderedBy: 'demo-doctor',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
    results: { value: 'Abnormal', unit: 'Various', status: 'critical' },
    priority: 'stat'
  }
];